/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  cpw.mods.fml.common.Loader
 *  cpw.mods.fml.common.registry.GameRegistry
 *  net.minecraft.creativetab.CreativeTabs
 *  net.minecraft.item.Item
 *  net.minecraft.item.Item$ToolMaterial
 *  net.minecraft.item.ItemAppleGold
 *  net.minecraft.item.ItemArmor$ArmorMaterial
 *  net.minecraft.potion.Potion
 *  net.minecraftforge.common.util.EnumHelper
 */
package net.minecraft.theTitans;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.item.Item;
import net.minecraft.item.ItemAppleGold;
import net.minecraft.item.ItemArmor;
import net.minecraft.potion.Potion;
import net.minecraft.theTitans.TheTitans;
import net.minecraft.theTitans.items.ItemAdamantium;
import net.minecraft.theTitans.items.ItemAdamantiumSword;
import net.minecraft.theTitans.items.ItemAdminiumArmor;
import net.minecraft.theTitans.items.ItemAdminiumAxe;
import net.minecraft.theTitans.items.ItemAdminiumHoe;
import net.minecraft.theTitans.items.ItemAdminiumPickaxe;
import net.minecraft.theTitans.items.ItemAdminiumSpade;
import net.minecraft.theTitans.items.ItemAdminiumSword;
import net.minecraft.theTitans.items.ItemAppleDiamond;
import net.minecraft.theTitans.items.ItemChaff;
import net.minecraft.theTitans.items.ItemCustomArmor;
import net.minecraft.theTitans.items.ItemCustomAxe;
import net.minecraft.theTitans.items.ItemCustomHoe;
import net.minecraft.theTitans.items.ItemCustomPickaxe;
import net.minecraft.theTitans.items.ItemCustomSpade;
import net.minecraft.theTitans.items.ItemCustomSword;
import net.minecraft.theTitans.items.ItemDiamondString;
import net.minecraft.theTitans.items.ItemEggBlazeTitan;
import net.minecraft.theTitans.items.ItemEggCaveSpiderTitan;
import net.minecraft.theTitans.items.ItemEggChargedCreeperTitan;
import net.minecraft.theTitans.items.ItemEggCreeperTitan;
import net.minecraft.theTitans.items.ItemEggEnderColossus;
import net.minecraft.theTitans.items.ItemEggGhastTitan;
import net.minecraft.theTitans.items.ItemEggMagmaCubeTitan;
import net.minecraft.theTitans.items.ItemEggOmegafish;
import net.minecraft.theTitans.items.ItemEggReinforcedIronGolem;
import net.minecraft.theTitans.items.ItemEggSkeletonTitan;
import net.minecraft.theTitans.items.ItemEggSlimeTitan;
import net.minecraft.theTitans.items.ItemEggSnowGolemTitan;
import net.minecraft.theTitans.items.ItemEggSpiderJockeyTitan;
import net.minecraft.theTitans.items.ItemEggSpiderTitan;
import net.minecraft.theTitans.items.ItemEggUltimaIronGolemTitan;
import net.minecraft.theTitans.items.ItemEggWitherJockeyTitan;
import net.minecraft.theTitans.items.ItemEggWitherSkeletonTitan;
import net.minecraft.theTitans.items.ItemEggWitherzilla;
import net.minecraft.theTitans.items.ItemEggZombiePigmanTitan;
import net.minecraft.theTitans.items.ItemEggZombieTitan;
import net.minecraft.theTitans.items.ItemFoodMalgrum;
import net.minecraft.theTitans.items.ItemForTheChallengeGames1;
import net.minecraft.theTitans.items.ItemGoodTurret;
import net.minecraft.theTitans.items.ItemGoodTurretGround;
import net.minecraft.theTitans.items.ItemGoodTurretMortar;
import net.minecraft.theTitans.items.ItemGrowthSerum;
import net.minecraft.theTitans.items.ItemHarcadium;
import net.minecraft.theTitans.items.ItemHarcadiumArmor;
import net.minecraft.theTitans.items.ItemHarcadiumArrow;
import net.minecraft.theTitans.items.ItemHarcadiumAxe;
import net.minecraft.theTitans.items.ItemHarcadiumBow;
import net.minecraft.theTitans.items.ItemHarcadiumHoe;
import net.minecraft.theTitans.items.ItemHarcadiumPickaxe;
import net.minecraft.theTitans.items.ItemHarcadiumSpade;
import net.minecraft.theTitans.items.ItemHarcadiumSword;
import net.minecraft.theTitans.items.ItemMalgrumSeeds;
import net.minecraft.theTitans.items.ItemOptimaAxe;
import net.minecraft.theTitans.items.ItemPleasantBladeBrew;
import net.minecraft.theTitans.items.ItemPleasantBladeFlower;
import net.minecraft.theTitans.items.ItemPleasantBladeSeed;
import net.minecraft.theTitans.items.ItemSpawnEggTitans;
import net.minecraft.theTitans.items.ItemTeleporter;
import net.minecraft.theTitans.items.ItemTeleporter2;
import net.minecraft.theTitans.items.ItemUltimaBlade;
import net.minecraft.theTitans.items.ItemVoid;
import net.minecraft.theTitans.items.ItemVoidArmor;
import net.minecraft.theTitans.items.ItemVoidAxe;
import net.minecraft.theTitans.items.ItemVoidHoe;
import net.minecraft.theTitans.items.ItemVoidPickaxe;
import net.minecraft.theTitans.items.ItemVoidSpade;
import net.minecraft.theTitans.items.ItemVoidSword;
import net.minecraftforge.common.util.EnumHelper;

public class TitanItems {
    public static ItemArmor.ArmorMaterial enumArmorMaterialAdminium = EnumHelper.addArmorMaterial((String)"AdminiumArmor", (int)100000000, (int[])new int[]{100000, 100000, 100000, 100000}, (int)60);
    public static ItemArmor.ArmorMaterial enumArmorMaterialAbsence = EnumHelper.addArmorMaterial((String)"AbsenceArmor", (int)100000, (int[])new int[]{11, 17, 13, 9}, (int)50);
    public static ItemArmor.ArmorMaterial enumArmorMaterialHarcadium = EnumHelper.addArmorMaterial((String)"HarcadiumArmor", (int)10000, (int[])new int[]{9, 15, 12, 8}, (int)30);
    public static ItemArmor.ArmorMaterial enumArmorMaterialSteel = EnumHelper.addArmorMaterial((String)"SteelArmor", (int)30, (int[])new int[]{3, 8, 6, 3}, (int)20);
    public static ItemArmor.ArmorMaterial enumArmorMaterialBronze = EnumHelper.addArmorMaterial((String)"BronzeArmor", (int)12, (int[])new int[]{2, 6, 4, 2}, (int)14);
    public static ItemArmor.ArmorMaterial enumArmorMaterialTin = EnumHelper.addArmorMaterial((String)"TinArmor", (int)6, (int[])new int[]{1, 3, 2, 1}, (int)18);
    public static ItemArmor.ArmorMaterial enumArmorMaterialCopper = EnumHelper.addArmorMaterial((String)"CopperArmor", (int)6, (int[])new int[]{1, 3, 2, 1}, (int)12);
    public static Item.ToolMaterial GoodTurret = EnumHelper.addToolMaterial((String)"GoodTurret", (int)0, (int)80, (float)0.0f, (float)26.0f, (int)50);
    public static Item.ToolMaterial enumToolMaterialAdminium = EnumHelper.addToolMaterial((String)"AdminiumTools", (int)Integer.MAX_VALUE, (int)1000000000, (float)1.0E9f, (float)1.0E9f, (int)60);
    public static Item.ToolMaterial enumToolMaterialAbsence = EnumHelper.addToolMaterial((String)"AbsenceTools", (int)100000000, (int)1000000, (float)4000.0f, (float)1496.0f, (int)40);
    public static Item.ToolMaterial enumToolMaterialHarcadium = EnumHelper.addToolMaterial((String)"HarcadiumTools", (int)1000, (int)75000, (float)120.0f, (float)46.0f, (int)30);
    public static Item.ToolMaterial enumToolMaterialSteel = EnumHelper.addToolMaterial((String)"SteelTools", (int)3, (int)900, (float)8.0f, (float)3.0f, (int)10);
    public static Item.ToolMaterial enumToolMaterialBronze = EnumHelper.addToolMaterial((String)"BronzeTools", (int)2, (int)200, (float)6.0f, (float)2.0f, (int)14);
    public static Item.ToolMaterial enumToolMaterialTin = EnumHelper.addToolMaterial((String)"TinTools", (int)1, (int)100, (float)3.0f, (float)1.0f, (int)18);
    public static Item.ToolMaterial enumToolMaterialCopper = EnumHelper.addToolMaterial((String)"CopperTools", (int)0, (int)80, (float)3.0f, (float)0.0f, (int)12);
    public static Item harcadium;
    public static Item harcadiumNugget;
    public static Item harcadiumWafer;
    public static Item harcadiumWaflet;
    public static Item harcadiumPickaxe;
    public static Item harcadiumAxe;
    public static Item harcadiumSpade;
    public static Item harcadiumHoe;
    public static Item harcadiumSword;
    public static Item harcadiumHelmet;
    public static Item harcadiumChestplate;
    public static Item harcadiumLeggings;
    public static Item harcadiumBoots;
    public static Item growthSerum;
    public static Item teleporter;
    public static Item teleporter2;
    public static Item goodTurret;
    public static Item goodTurret2;
    public static Item goodTurret3;
    public static Item goldenPotatoe;
    public static Item goldenCookie;
    public static Item goldenBread;
    public static Item goldenMelon;
    public static Item goldenPumpkinPie;
    public static Item diamondApple;
    public static Item diamondPotatoe;
    public static Item diamondCookie;
    public static Item diamondBread;
    public static Item diamondMelon;
    public static Item diamondPumpkinPie;
    public static Item malgrum;
    public static Item malgrumSeeds;
    public static Item pleasantBladeSeed;
    public static Item pleasantBladeLeaf;
    public static Item pleasantBladeFlower;
    public static Item pleasantBladeBrew;
    public static Item chaff;
    public static Item diamondString;
    public static Item harcadiumArrow;
    public static Item harcadiumBow;
    public static Item witherSkeletonSpawner;
    public static Item eggOmegafish;
    public static Item eggCaveSpiderTitan;
    public static Item eggSpiderTitan;
    public static Item eggSpiderJockeyTitan;
    public static Item eggSlimeTitan;
    public static Item eggMagmaCubeTitan;
    public static Item eggZombieTitan;
    public static Item eggSkeletonTitan;
    public static Item eggCreeperTitan;
    public static Item eggChargedCreeperTitan;
    public static Item eggZombiePigmanTitan;
    public static Item eggBlazeTitan;
    public static Item eggWitherSkeletonTitan;
    public static Item eggWitherJockeyTitan;
    public static Item eggGhastTitan;
    public static Item eggEnderColossus;
    public static Item eggWitherzilla;
    public static Item ultimaBlade;
    public static Item optimaAxe;
    public static Item adamantiumSword;
    public static Item eggUltimaIronGolemTitan;
    public static Item eggIronGolemBetter;
    public static Item eggSnowGolemTitan;
    public static Item adminiumHelmet;
    public static Item adminiumChestplate;
    public static Item adminiumLeggings;
    public static Item adminiumBoots;
    public static Item adminiumPickaxe;
    public static Item adminiumAxe;
    public static Item adminiumSpade;
    public static Item adminiumHoe;
    public static Item adminiumSword;
    public static Item voidItem;
    public static Item voidHelmet;
    public static Item voidChestplate;
    public static Item voidLeggings;
    public static Item voidBoots;
    public static Item voidPickaxe;
    public static Item voidAxe;
    public static Item voidSpade;
    public static Item voidHoe;
    public static Item voidSword;
    public static Item copperIngot;
    public static Item copperPickaxe;
    public static Item copperAxe;
    public static Item copperSpade;
    public static Item copperHoe;
    public static Item copperSword;
    public static Item copperHelmet;
    public static Item copperChestplate;
    public static Item copperLeggings;
    public static Item copperBoots;
    public static Item tinIngot;
    public static Item tinPickaxe;
    public static Item tinAxe;
    public static Item tinSpade;
    public static Item tinHoe;
    public static Item tinSword;
    public static Item tinHelmet;
    public static Item tinChestplate;
    public static Item tinLeggings;
    public static Item tinBoots;
    public static Item bronzeIngot;
    public static Item bronzePickaxe;
    public static Item bronzeAxe;
    public static Item bronzeSpade;
    public static Item bronzeHoe;
    public static Item bronzeSword;
    public static Item bronzeHelmet;
    public static Item bronzeChestplate;
    public static Item bronzeLeggings;
    public static Item bronzeBoots;
    public static Item steelIngot;
    public static Item steelPickaxe;
    public static Item steelAxe;
    public static Item steelSpade;
    public static Item steelHoe;
    public static Item steelSword;
    public static Item steelHelmet;
    public static Item steelChestplate;
    public static Item steelLeggings;
    public static Item steelBoots;
    public static Item chromiumIngot;
    public static Item magnesiumIngot;
    public static Item leadIngot;
    public static Item silverIngot;
    public static Item platinumIngot;
    public static Item ruby;
    public static Item onyx;
    public static Item adamantium;
    public static Item OverlordScorpionEgg;
    public static Item MethuselahKrakenEgg;

    public static void init() {
        ultimaBlade = new ItemUltimaBlade("ultima_blade");
        optimaAxe = new ItemOptimaAxe("optima_axe");
        adamantiumSword = new ItemAdamantiumSword("adamantium_sword");
        harcadiumWaflet = new ItemHarcadium("harcadium_waflet");
        harcadiumWafer = new ItemHarcadium("harcadium_wafer");
        harcadiumNugget = new ItemHarcadium("harcadium_nugget");
        harcadium = new ItemHarcadium("harcadium");
        voidItem = new ItemVoid("void");
        adamantium = new ItemAdamantium("adamantium");
        copperIngot = new Item().setUnlocalizedName("copper_ingot").setTextureName("thetitans:copper_ingot").setCreativeTab(TheTitans.titansTab);
        copperPickaxe = new ItemCustomPickaxe("copper_pickaxe", enumToolMaterialCopper);
        copperAxe = new ItemCustomAxe("copper_axe", enumToolMaterialCopper);
        copperSpade = new ItemCustomSpade("copper_spade", enumToolMaterialCopper);
        copperHoe = new ItemCustomHoe("copper_hoe", enumToolMaterialCopper);
        copperSword = new ItemCustomSword("copper_sword", enumToolMaterialCopper);
        copperHelmet = new ItemCustomArmor("copper_helmet", enumArmorMaterialCopper, 0, "copper_layer_");
        copperChestplate = new ItemCustomArmor("copper_chestplate", enumArmorMaterialCopper, 1, "copper_layer_");
        copperLeggings = new ItemCustomArmor("copper_leggings", enumArmorMaterialCopper, 2, "copper_layer_");
        copperBoots = new ItemCustomArmor("copper_boots", enumArmorMaterialCopper, 3, "copper_layer_");
        tinIngot = new Item().setUnlocalizedName("tin_ingot").setTextureName("thetitans:tin_ingot").setCreativeTab(TheTitans.titansTab);
        tinPickaxe = new ItemCustomPickaxe("tin_pickaxe", enumToolMaterialTin);
        tinAxe = new ItemCustomAxe("tin_axe", enumToolMaterialTin);
        tinSpade = new ItemCustomSpade("tin_spade", enumToolMaterialTin);
        tinHoe = new ItemCustomHoe("tin_hoe", enumToolMaterialTin);
        tinSword = new ItemCustomSword("tin_sword", enumToolMaterialTin);
        tinHelmet = new ItemCustomArmor("tin_helmet", enumArmorMaterialTin, 0, "tin_layer_");
        tinChestplate = new ItemCustomArmor("tin_chestplate", enumArmorMaterialTin, 1, "tin_layer_");
        tinLeggings = new ItemCustomArmor("tin_leggings", enumArmorMaterialTin, 2, "tin_layer_");
        tinBoots = new ItemCustomArmor("tin_boots", enumArmorMaterialTin, 3, "tin_layer_");
        bronzeIngot = new Item().setUnlocalizedName("bronze_ingot").setTextureName("thetitans:bronze_ingot").setCreativeTab(TheTitans.titansTab);
        bronzePickaxe = new ItemCustomPickaxe("bronze_pickaxe", enumToolMaterialBronze);
        bronzeAxe = new ItemCustomAxe("bronze_axe", enumToolMaterialBronze);
        bronzeSpade = new ItemCustomSpade("bronze_spade", enumToolMaterialBronze);
        bronzeHoe = new ItemCustomHoe("bronze_hoe", enumToolMaterialBronze);
        bronzeSword = new ItemCustomSword("bronze_sword", enumToolMaterialBronze);
        bronzeHelmet = new ItemCustomArmor("bronze_helmet", enumArmorMaterialBronze, 0, "bronze_layer_");
        bronzeChestplate = new ItemCustomArmor("bronze_chestplate", enumArmorMaterialBronze, 1, "bronze_layer_");
        bronzeLeggings = new ItemCustomArmor("bronze_leggings", enumArmorMaterialBronze, 2, "bronze_layer_");
        bronzeBoots = new ItemCustomArmor("bronze_boots", enumArmorMaterialBronze, 3, "bronze_layer_");
        steelIngot = new Item().setUnlocalizedName("steel_ingot").setTextureName("thetitans:steel_ingot").setCreativeTab(TheTitans.titansTab);
        steelPickaxe = new ItemCustomPickaxe("steel_pickaxe", enumToolMaterialSteel);
        steelAxe = new ItemCustomAxe("steel_axe", enumToolMaterialSteel);
        steelSpade = new ItemCustomSpade("steel_spade", enumToolMaterialSteel);
        steelHoe = new ItemCustomHoe("steel_hoe", enumToolMaterialSteel);
        steelSword = new ItemCustomSword("steel_sword", enumToolMaterialSteel);
        steelHelmet = new ItemCustomArmor("steel_helmet", enumArmorMaterialSteel, 0, "steel_layer_");
        steelChestplate = new ItemCustomArmor("steel_chestplate", enumArmorMaterialSteel, 1, "steel_layer_");
        steelLeggings = new ItemCustomArmor("steel_leggings", enumArmorMaterialSteel, 2, "steel_layer_");
        steelBoots = new ItemCustomArmor("steel_boots", enumArmorMaterialSteel, 3, "steel_layer_");
        chromiumIngot = new Item().setUnlocalizedName("chromium_ingot").setTextureName("thetitans:chromium_ingot").setCreativeTab(TheTitans.titansTab);
        magnesiumIngot = new Item().setUnlocalizedName("magnesium_ingot").setTextureName("thetitans:magnesium_ingot").setCreativeTab(TheTitans.titansTab);
        leadIngot = new Item().setUnlocalizedName("lead_ingot").setTextureName("thetitans:lead_ingot").setCreativeTab(TheTitans.titansTab);
        silverIngot = new Item().setUnlocalizedName("silver_ingot").setTextureName("thetitans:silver_ingot").setCreativeTab(TheTitans.titansTab);
        platinumIngot = new Item().setUnlocalizedName("platinum_ingot").setTextureName("thetitans:platinum_ingot").setCreativeTab(TheTitans.titansTab);
        harcadiumBow = new ItemHarcadiumBow();
        harcadiumPickaxe = new ItemHarcadiumPickaxe("harcadium_pickaxe", enumToolMaterialHarcadium);
        harcadiumAxe = new ItemHarcadiumAxe("harcadium_axe", enumToolMaterialHarcadium);
        harcadiumSpade = new ItemHarcadiumSpade("harcadium_spade", enumToolMaterialHarcadium);
        harcadiumHoe = new ItemHarcadiumHoe("harcadium_hoe", enumToolMaterialHarcadium);
        harcadiumSword = new ItemHarcadiumSword("harcadium_sword", enumToolMaterialHarcadium);
        harcadiumHelmet = new ItemHarcadiumArmor("harcadium_helmet", enumArmorMaterialHarcadium, 0);
        harcadiumChestplate = new ItemHarcadiumArmor("harcadium_chestplate", enumArmorMaterialHarcadium, 1);
        harcadiumLeggings = new ItemHarcadiumArmor("harcadium_leggings", enumArmorMaterialHarcadium, 2);
        harcadiumBoots = new ItemHarcadiumArmor("harcadium_boots", enumArmorMaterialHarcadium, 3);
        growthSerum = new ItemGrowthSerum("growth_serum");
        teleporter = new ItemTeleporter("teleporter");
        teleporter2 = new ItemTeleporter2("teleporter2");
        goodTurret = new ItemGoodTurret("turret_good", GoodTurret);
        goodTurret2 = new ItemGoodTurretGround("machine_gun_good", GoodTurret);
        goodTurret3 = new ItemGoodTurretMortar("mortar_good", GoodTurret);
        goldenPotatoe = new ItemAppleGold(6, 1.2f, false).setAlwaysEdible().setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setUnlocalizedName("golden_potatoe").setTextureName("thetitans:golden_potatoe").setCreativeTab(TheTitans.titansTab);
        goldenBread = new ItemAppleGold(5, 1.2f, false).setAlwaysEdible().setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setUnlocalizedName("golden_bread").setTextureName("thetitans:golden_bread").setCreativeTab(TheTitans.titansTab);
        goldenCookie = new ItemAppleGold(2, 1.2f, false).setAlwaysEdible().setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setUnlocalizedName("golden_cookie").setTextureName("thetitans:golden_cookie").setCreativeTab(TheTitans.titansTab);
        goldenMelon = new ItemAppleGold(2, 1.2f, false).setAlwaysEdible().setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setUnlocalizedName("golden_melon").setTextureName("thetitans:golden_melon").setCreativeTab(TheTitans.titansTab);
        goldenPumpkinPie = new ItemAppleGold(8, 1.2f, false).setAlwaysEdible().setPotionEffect(Potion.regeneration.id, 5, 1, 1.0f).setUnlocalizedName("golden_pumpkin_pie").setTextureName("thetitans:golden_pumpkin_pie").setCreativeTab(TheTitans.titansTab);
        diamondApple = new ItemAppleDiamond(4, 2.4f, false).setAlwaysEdible().setUnlocalizedName("apple_diamond").setTextureName("thetitans:apple_diamond").setCreativeTab(CreativeTabs.tabFood);
        diamondPotatoe = new ItemAppleDiamond(6, 2.4f, false).setAlwaysEdible().setUnlocalizedName("diamond_potatoe").setTextureName("thetitans:diamond_potatoe").setCreativeTab(TheTitans.titansTab);
        diamondBread = new ItemAppleDiamond(5, 2.4f, false).setAlwaysEdible().setUnlocalizedName("diamond_bread").setTextureName("thetitans:diamond_bread").setCreativeTab(TheTitans.titansTab);
        diamondCookie = new ItemAppleDiamond(2, 2.4f, false).setAlwaysEdible().setUnlocalizedName("diamond_cookie").setTextureName("thetitans:diamond_cookie").setCreativeTab(TheTitans.titansTab);
        diamondMelon = new ItemAppleDiamond(2, 2.4f, false).setAlwaysEdible().setUnlocalizedName("diamond_melon").setTextureName("thetitans:diamond_melon").setCreativeTab(TheTitans.titansTab);
        diamondPumpkinPie = new ItemAppleDiamond(8, 2.4f, false).setAlwaysEdible().setUnlocalizedName("diamond_pumpkin_pie").setTextureName("thetitans:diamond_pumpkin_pie").setCreativeTab(TheTitans.titansTab);
        malgrum = new ItemFoodMalgrum(20, 20.0f, false).setAlwaysEdible().setUnlocalizedName("malgrum_fruit").setTextureName("thetitans:malgrum_fruit").setCreativeTab(TheTitans.titansTab);
        malgrumSeeds = new ItemMalgrumSeeds();
        pleasantBladeBrew = new ItemPleasantBladeBrew();
        pleasantBladeFlower = new ItemPleasantBladeFlower(2, 1.2f, false).setUnlocalizedName("pleasant_blade_flower").setTextureName("thetitans:pleasant_blade_flower").setCreativeTab(TheTitans.titansTab);
        pleasantBladeLeaf = new Item().setUnlocalizedName("pleasant_blade_leaf").setTextureName("thetitans:pleasant_blade_leaf").setCreativeTab(TheTitans.titansTab);
        pleasantBladeSeed = new ItemPleasantBladeSeed();
        chaff = new ItemChaff("chaff");
        diamondString = new ItemDiamondString("diamond_string");
        harcadiumArrow = new ItemHarcadiumArrow("harcadium_arrow");
        witherSkeletonSpawner = new ItemForTheChallengeGames1("witherskeletonspawn");
        eggIronGolemBetter = new ItemEggReinforcedIronGolem("spawn_egg_iron_golem_better");
        eggSnowGolemTitan = new ItemEggSnowGolemTitan("spawn_egg_snow_golem_titan");
        eggSlimeTitan = new ItemEggSlimeTitan("spawn_egg_slime_titan");
        eggMagmaCubeTitan = new ItemEggMagmaCubeTitan("spawn_egg_magma_cube_titan");
        eggOmegafish = new ItemEggOmegafish("spawn_egg_omegafish");
        eggCaveSpiderTitan = new ItemEggCaveSpiderTitan("spawn_egg_cave_spider_titan");
        eggSpiderTitan = new ItemEggSpiderTitan("spawn_egg_spider_titan");
        eggSpiderJockeyTitan = new ItemEggSpiderJockeyTitan("spawn_egg_spider_jockey_titan");
        eggZombieTitan = new ItemEggZombieTitan("spawn_egg_zombie_titan");
        eggSkeletonTitan = new ItemEggSkeletonTitan("spawn_egg_skeleton_titan");
        eggCreeperTitan = new ItemEggCreeperTitan("spawn_egg_creeper_titan");
        eggChargedCreeperTitan = new ItemEggChargedCreeperTitan("spawn_egg_charged_creeper_titan");
        eggZombiePigmanTitan = new ItemEggZombiePigmanTitan("spawn_egg_zombie_pigman_titan");
        eggBlazeTitan = new ItemEggBlazeTitan("spawn_egg_blaze_titan");
        eggWitherSkeletonTitan = new ItemEggWitherSkeletonTitan("spawn_egg_wither_skeleton_titan");
        eggWitherJockeyTitan = new ItemEggWitherJockeyTitan("spawn_egg_wither_jockey_titan");
        eggEnderColossus = new ItemEggEnderColossus("spawn_egg_ender_colossus");
        eggGhastTitan = new ItemEggGhastTitan("spawn_egg_ghast_titan");
        eggUltimaIronGolemTitan = new ItemEggUltimaIronGolemTitan("spawn_egg_iron_golem_titan");
        eggWitherzilla = new ItemEggWitherzilla("spawn_egg_witherzilla");
        adminiumHelmet = new ItemAdminiumArmor("adminium_helmet", enumArmorMaterialAdminium, 0);
        adminiumChestplate = new ItemAdminiumArmor("adminium_chestplate", enumArmorMaterialAdminium, 1);
        adminiumLeggings = new ItemAdminiumArmor("adminium_leggings", enumArmorMaterialAdminium, 2);
        adminiumBoots = new ItemAdminiumArmor("adminium_boots", enumArmorMaterialAdminium, 3);
        adminiumPickaxe = new ItemAdminiumPickaxe("adminium_pickaxe", enumToolMaterialAdminium);
        adminiumAxe = new ItemAdminiumAxe("adminium_axe", enumToolMaterialAdminium);
        adminiumSpade = new ItemAdminiumSpade("adminium_spade", enumToolMaterialAdminium);
        adminiumHoe = new ItemAdminiumHoe("adminium_hoe", enumToolMaterialAdminium);
        adminiumSword = new ItemAdminiumSword("adminium_sword", enumToolMaterialAdminium);
        voidPickaxe = new ItemVoidPickaxe("void_pickaxe", enumToolMaterialAbsence);
        voidAxe = new ItemVoidAxe("void_axe", enumToolMaterialAbsence);
        voidSpade = new ItemVoidSpade("void_spade", enumToolMaterialAbsence);
        voidHoe = new ItemVoidHoe("void_hoe", enumToolMaterialAbsence);
        voidSword = new ItemVoidSword("void_sword", enumToolMaterialAbsence);
        voidHelmet = new ItemVoidArmor("void_helmet", enumArmorMaterialAbsence, 0);
        voidChestplate = new ItemVoidArmor("void_chestplate", enumArmorMaterialAbsence, 1);
        voidLeggings = new ItemVoidArmor("void_leggings", enumArmorMaterialAbsence, 2);
        voidBoots = new ItemVoidArmor("void_boots", enumArmorMaterialAbsence, 3);
        GameRegistry.registerItem((Item)ultimaBlade, (String)ultimaBlade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)optimaAxe, (String)optimaAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adamantium, (String)adamantium.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumHelmet, (String)adminiumHelmet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumChestplate, (String)adminiumChestplate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumLeggings, (String)adminiumLeggings.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumBoots, (String)adminiumBoots.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumSword, (String)adminiumSword.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumAxe, (String)adminiumAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumPickaxe, (String)adminiumPickaxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumSpade, (String)adminiumSpade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)adminiumHoe, (String)adminiumHoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidItem, (String)voidItem.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidHelmet, (String)voidHelmet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidChestplate, (String)voidChestplate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidLeggings, (String)voidLeggings.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidBoots, (String)voidBoots.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidSword, (String)voidSword.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidAxe, (String)voidAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidPickaxe, (String)voidPickaxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidSpade, (String)voidSpade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)voidHoe, (String)voidHoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)diamondString, (String)diamondString.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumWaflet, (String)harcadiumWaflet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumWafer, (String)harcadiumWafer.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumNugget, (String)harcadiumNugget.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadium, (String)harcadium.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumBow, (String)harcadiumBow.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumArrow, (String)harcadiumArrow.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumHelmet, (String)harcadiumHelmet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumChestplate, (String)harcadiumChestplate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumLeggings, (String)harcadiumLeggings.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumBoots, (String)harcadiumBoots.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumSword, (String)harcadiumSword.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumAxe, (String)harcadiumAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumPickaxe, (String)harcadiumPickaxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumSpade, (String)harcadiumSpade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)harcadiumHoe, (String)harcadiumHoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperIngot, (String)copperIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperHelmet, (String)copperHelmet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperChestplate, (String)copperChestplate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperLeggings, (String)copperLeggings.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperBoots, (String)copperBoots.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperSword, (String)copperSword.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperAxe, (String)copperAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperPickaxe, (String)copperPickaxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperSpade, (String)copperSpade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)copperHoe, (String)copperHoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinIngot, (String)tinIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinHelmet, (String)tinHelmet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinChestplate, (String)tinChestplate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinLeggings, (String)tinLeggings.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinBoots, (String)tinBoots.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinSword, (String)tinSword.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinAxe, (String)tinAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinPickaxe, (String)tinPickaxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinSpade, (String)tinSpade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)tinHoe, (String)tinHoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeIngot, (String)bronzeIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeHelmet, (String)bronzeHelmet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeChestplate, (String)bronzeChestplate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeLeggings, (String)bronzeLeggings.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeBoots, (String)bronzeBoots.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeSword, (String)bronzeSword.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeAxe, (String)bronzeAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzePickaxe, (String)bronzePickaxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeSpade, (String)bronzeSpade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)bronzeHoe, (String)bronzeHoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelIngot, (String)steelIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelHelmet, (String)steelHelmet.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelChestplate, (String)steelChestplate.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelLeggings, (String)steelLeggings.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelBoots, (String)steelBoots.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelSword, (String)steelSword.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelAxe, (String)steelAxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelPickaxe, (String)steelPickaxe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelSpade, (String)steelSpade.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)steelHoe, (String)steelHoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chromiumIngot, (String)chromiumIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)magnesiumIngot, (String)magnesiumIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)leadIngot, (String)leadIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)silverIngot, (String)silverIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)platinumIngot, (String)platinumIngot.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)growthSerum, (String)growthSerum.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)teleporter, (String)teleporter.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)teleporter2, (String)teleporter2.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goodTurret, (String)goodTurret.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goodTurret2, (String)goodTurret2.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goodTurret3, (String)goodTurret3.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)malgrum, (String)malgrum.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)malgrumSeeds, (String)malgrumSeeds.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pleasantBladeBrew, (String)pleasantBladeBrew.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pleasantBladeFlower, (String)pleasantBladeFlower.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pleasantBladeLeaf, (String)pleasantBladeLeaf.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)pleasantBladeSeed, (String)pleasantBladeSeed.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)chaff, (String)chaff.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goldenPotatoe, (String)goldenPotatoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goldenBread, (String)goldenBread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goldenCookie, (String)goldenCookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goldenMelon, (String)goldenMelon.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)goldenPumpkinPie, (String)goldenPumpkinPie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)diamondApple, (String)diamondApple.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)diamondPotatoe, (String)diamondPotatoe.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)diamondBread, (String)diamondBread.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)diamondCookie, (String)diamondCookie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)diamondMelon, (String)diamondMelon.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)diamondPumpkinPie, (String)diamondPumpkinPie.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)witherSkeletonSpawner, (String)witherSkeletonSpawner.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggIronGolemBetter, (String)eggIronGolemBetter.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggSnowGolemTitan, (String)eggSnowGolemTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggSlimeTitan, (String)eggSlimeTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggMagmaCubeTitan, (String)eggMagmaCubeTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggOmegafish, (String)eggOmegafish.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggCaveSpiderTitan, (String)eggCaveSpiderTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggSpiderTitan, (String)eggSpiderTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggSpiderJockeyTitan, (String)eggSpiderJockeyTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggZombieTitan, (String)eggZombieTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggSkeletonTitan, (String)eggSkeletonTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggCreeperTitan, (String)eggCreeperTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggChargedCreeperTitan, (String)eggChargedCreeperTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggZombiePigmanTitan, (String)eggZombiePigmanTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggBlazeTitan, (String)eggBlazeTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggWitherSkeletonTitan, (String)eggWitherSkeletonTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggWitherJockeyTitan, (String)eggWitherJockeyTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggEnderColossus, (String)eggEnderColossus.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggGhastTitan, (String)eggGhastTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggUltimaIronGolemTitan, (String)eggUltimaIronGolemTitan.getUnlocalizedName().substring(5));
        GameRegistry.registerItem((Item)eggWitherzilla, (String)eggWitherzilla.getUnlocalizedName().substring(5));
        if (Loader.isModLoaded((String)"OreSpawn")) {
            OverlordScorpionEgg = new ItemSpawnEggTitans("eggoverlordscorpion", 384);
            MethuselahKrakenEgg = new ItemSpawnEggTitans("eggelderkraken", 385);
            GameRegistry.registerItem((Item)OverlordScorpionEgg, (String)OverlordScorpionEgg.getUnlocalizedName().substring(5));
            GameRegistry.registerItem((Item)MethuselahKrakenEgg, (String)MethuselahKrakenEgg.getUnlocalizedName().substring(5));
        }
    }
}

