/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.titan.EntitySpiderTitan;
import net.minecraft.util.MathHelper;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelSpiderTitan
extends ModelBase {
    public ModelRenderer Thorax;
    public ModelRenderer Head;
    public ModelRenderer Abdoman;
    public ModelRenderer Frontleftupperarm;
    public ModelRenderer Frontrightupperarm;
    public ModelRenderer Frontleftupperleg;
    public ModelRenderer Frontrightupperleg;
    public ModelRenderer Backrightupperleg1;
    public ModelRenderer Backrightupperleg2;
    public ModelRenderer Backleftupperleg1;
    public ModelRenderer Backleftupperleg2;
    public ModelRenderer Frontleftlowerarm;
    public ModelRenderer Frontrightlowerarm;
    public ModelRenderer Frontleftlowerleg;
    public ModelRenderer Frontrightlowerleg;
    public ModelRenderer Backrightlowerleg1;
    public ModelRenderer Backrightlowerleg2;
    public ModelRenderer Backleftlowerleg1;
    public ModelRenderer Backleftlowerleg2;
    private Animator animator;

    public ModelSpiderTitan() {
        this(0.0f);
    }

    public ModelSpiderTitan(float p_i1147_1_) {
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.Head = new ModelRenderer((ModelBase)this, 0, 0);
        this.Head.setRotationPoint(0.0f, 0.0f, -3.0f);
        this.Head.addBox(-4.0f, -4.0f, -8.0f, 8, 8, 8, p_i1147_1_);
        this.Backleftlowerleg1 = new ModelRenderer((ModelBase)this, 32, 10);
        this.Backleftlowerleg1.mirror = true;
        this.Backleftlowerleg1.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Backleftlowerleg1.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Abdoman = new ModelRenderer((ModelBase)this, 0, 28);
        this.Abdoman.setRotationPoint(0.0f, 0.0f, 3.0f);
        this.Abdoman.addBox(-5.0f, -4.0f, 0.0f, 10, 8, 12, p_i1147_1_);
        this.Backrightupperleg1 = new ModelRenderer((ModelBase)this, 32, 0);
        this.Backrightupperleg1.setRotationPoint(-3.0f, 0.0f, 1.0f);
        this.Backrightupperleg1.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Backleftupperleg2 = new ModelRenderer((ModelBase)this, 32, 0);
        this.Backleftupperleg2.mirror = true;
        this.Backleftupperleg2.setRotationPoint(3.0f, 0.0f, 2.0f);
        this.Backleftupperleg2.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Thorax = new ModelRenderer((ModelBase)this, 0, 16);
        this.Thorax.setRotationPoint(0.0f, 15.0f, 0.0f);
        this.Thorax.addBox(-3.0f, -3.0f, -3.0f, 6, 6, 6, p_i1147_1_);
        this.Frontleftlowerarm = new ModelRenderer((ModelBase)this, 32, 10);
        this.Frontleftlowerarm.mirror = true;
        this.Frontleftlowerarm.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Frontleftlowerarm.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Backrightupperleg2 = new ModelRenderer((ModelBase)this, 32, 0);
        this.Backrightupperleg2.setRotationPoint(-3.0f, 0.0f, 2.0f);
        this.Backrightupperleg2.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Frontleftupperleg = new ModelRenderer((ModelBase)this, 32, 0);
        this.Frontleftupperleg.mirror = true;
        this.Frontleftupperleg.setRotationPoint(3.0f, 0.0f, -1.0f);
        this.Frontleftupperleg.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Backrightlowerleg2 = new ModelRenderer((ModelBase)this, 32, 10);
        this.Backrightlowerleg2.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Backrightlowerleg2.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Frontrightupperleg = new ModelRenderer((ModelBase)this, 32, 0);
        this.Frontrightupperleg.setRotationPoint(-3.0f, 0.0f, -1.0f);
        this.Frontrightupperleg.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Frontrightlowerarm = new ModelRenderer((ModelBase)this, 32, 10);
        this.Frontrightlowerarm.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Frontrightlowerarm.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Frontleftlowerleg = new ModelRenderer((ModelBase)this, 32, 10);
        this.Frontleftlowerleg.mirror = true;
        this.Frontleftlowerleg.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Frontleftlowerleg.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Backleftlowerleg2 = new ModelRenderer((ModelBase)this, 32, 10);
        this.Backleftlowerleg2.mirror = true;
        this.Backleftlowerleg2.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Backleftlowerleg2.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Frontleftupperarm = new ModelRenderer((ModelBase)this, 32, 0);
        this.Frontleftupperarm.mirror = true;
        this.Frontleftupperarm.setRotationPoint(3.0f, 0.0f, -2.0f);
        this.Frontleftupperarm.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Frontrightupperarm = new ModelRenderer((ModelBase)this, 32, 0);
        this.Frontrightupperarm.setRotationPoint(-3.0f, 0.0f, -2.0f);
        this.Frontrightupperarm.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Backleftupperleg1 = new ModelRenderer((ModelBase)this, 32, 0);
        this.Backleftupperleg1.mirror = true;
        this.Backleftupperleg1.setRotationPoint(3.0f, 0.0f, 1.0f);
        this.Backleftupperleg1.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Frontrightlowerleg = new ModelRenderer((ModelBase)this, 32, 10);
        this.Frontrightlowerleg.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Frontrightlowerleg.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Backrightlowerleg1 = new ModelRenderer((ModelBase)this, 32, 10);
        this.Backrightlowerleg1.setRotationPoint(0.0f, 8.0f, 0.0f);
        this.Backrightlowerleg1.addBox(-1.0f, 0.0f, -1.0f, 2, 8, 2, p_i1147_1_);
        this.Thorax.addChild(this.Head);
        this.Backleftupperleg1.addChild(this.Backleftlowerleg1);
        this.Thorax.addChild(this.Abdoman);
        this.Thorax.addChild(this.Backrightupperleg1);
        this.Thorax.addChild(this.Backleftupperleg2);
        this.Frontleftupperarm.addChild(this.Frontleftlowerarm);
        this.Thorax.addChild(this.Backrightupperleg2);
        this.Thorax.addChild(this.Frontleftupperleg);
        this.Backrightupperleg2.addChild(this.Backrightlowerleg2);
        this.Thorax.addChild(this.Frontrightupperleg);
        this.Frontrightupperarm.addChild(this.Frontrightlowerarm);
        this.Frontleftupperleg.addChild(this.Frontleftlowerleg);
        this.Backleftupperleg2.addChild(this.Backleftlowerleg2);
        this.Thorax.addChild(this.Frontleftupperarm);
        this.Thorax.addChild(this.Frontrightupperarm);
        this.Thorax.addChild(this.Backleftupperleg1);
        this.Frontrightupperleg.addChild(this.Frontrightlowerleg);
        this.Backrightupperleg1.addChild(this.Backrightlowerleg1);
        this.animator = new Animator(this);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntitySpiderTitan spiderTitan = (EntitySpiderTitan)entity;
        this.animate(spiderTitan, f, f1, f2, f3, f4, f5);
        this.Thorax.render(f5);
    }

    public void setAngles() {
        this.Thorax.rotationPointY = 15.0f;
        this.Thorax.rotationPointX = 0.0f;
        this.Thorax.rotationPointZ = 0.0f;
        this.Head.rotateAngleX = 0.0f;
        this.Thorax.rotateAngleX = 0.0f;
        this.Abdoman.rotateAngleX = 0.0f;
        this.Frontrightupperarm.rotateAngleX = -1.2217305f;
        this.Frontrightupperarm.rotateAngleY = 0.87266463f;
        this.Frontleftupperarm.rotateAngleX = -1.2217305f;
        this.Frontleftupperarm.rotateAngleY = -0.87266463f;
        this.Frontrightlowerarm.rotateAngleX = 0.475f;
        this.Frontleftlowerarm.rotateAngleX = 0.475f;
        this.Frontleftupperleg.rotateAngleX = -1.2217305f;
        this.Frontleftupperleg.rotateAngleY = -1.3089969f;
        this.Frontrightupperleg.rotateAngleX = -1.2217305f;
        this.Frontrightupperleg.rotateAngleY = 1.3089969f;
        this.Frontleftlowerleg.rotateAngleX = 0.475f;
        this.Frontrightlowerleg.rotateAngleX = 0.475f;
        this.Backleftupperleg1.rotateAngleX = -1.2217305f;
        this.Backleftupperleg1.rotateAngleY = -1.8325957f;
        this.Backrightupperleg1.rotateAngleX = -1.2217305f;
        this.Backrightupperleg1.rotateAngleY = 1.8325957f;
        this.Backleftlowerleg1.rotateAngleX = 0.475f;
        this.Backrightlowerleg1.rotateAngleX = 0.475f;
        this.Backleftupperleg2.rotateAngleX = -1.2217305f;
        this.Backleftupperleg2.rotateAngleY = -2.1816616f;
        this.Backrightupperleg2.rotateAngleX = -1.2217305f;
        this.Backrightupperleg2.rotateAngleY = 2.1816616f;
        this.Backleftlowerleg2.rotateAngleX = 0.475f;
        this.Backrightlowerleg2.rotateAngleX = 0.475f;
    }

    public void animate(EntitySpiderTitan spider, float f, float f1, float f2, float f3, float f4, float f5) {
        this.animator.update(spider);
        this.setAngles();
        if (spider.deathTicks <= 0) {
            if (this.isRiding) {
                this.Frontrightupperarm.rotateAngleY = 0.87266463f;
                this.Frontleftupperarm.rotateAngleY = -0.87266463f;
                this.Frontrightupperleg.rotateAngleY = 1.3089969f;
                this.Frontleftupperleg.rotateAngleY = -1.3089969f;
                this.Backrightupperleg1.rotateAngleY = 1.8325957f;
                this.Backleftupperleg1.rotateAngleY = -1.8325957f;
                this.Backrightupperleg2.rotateAngleY = 2.1816616f;
                this.Backleftupperleg2.rotateAngleY = -2.1816616f;
                this.Frontrightupperarm.rotateAngleX = -0.8f;
                this.Frontleftupperarm.rotateAngleX = -0.8f;
                this.Frontrightupperleg.rotateAngleX = -0.8f;
                this.Frontleftupperleg.rotateAngleX = -0.8f;
                this.Backrightupperleg1.rotateAngleX = -0.8f;
                this.Backleftupperleg1.rotateAngleX = -0.8f;
                this.Backrightupperleg2.rotateAngleX = -0.8f;
                this.Backleftupperleg2.rotateAngleX = -0.8f;
            } else if (spider.getAnimID() == 0) {
                this.Frontrightupperarm.rotateAngleY = 0.87266463f + MathHelper.cos((float)(f * 0.5f + 2.0f)) * 0.3f * f1;
                this.Frontleftupperarm.rotateAngleY = -0.87266463f + MathHelper.cos((float)(f * 0.5f + 4.0f)) * 0.3f * f1;
                this.Frontrightupperleg.rotateAngleY = 1.3089969f + MathHelper.cos((float)(f * 0.5f + 6.0f)) * 0.3f * f1;
                this.Frontleftupperleg.rotateAngleY = -1.3089969f + MathHelper.cos((float)(f * 0.5f)) * 0.3f * f1;
                this.Backrightupperleg1.rotateAngleY = 1.8325957f + MathHelper.cos((float)(f * 0.5f + 6.0f)) * 0.3f * f1;
                this.Backleftupperleg1.rotateAngleY = -1.8325957f + MathHelper.cos((float)(f * 0.5f + 4.0f)) * 0.3f * f1;
                this.Backrightupperleg2.rotateAngleY = 2.1816616f + MathHelper.cos((float)(f * 0.5f + 2.0f)) * 0.3f * f1;
                this.Backleftupperleg2.rotateAngleY = -2.1816616f + MathHelper.cos((float)(f * 0.5f)) * 0.3f * f1;
                this.Frontrightupperarm.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f + 2.0f)) * 0.15f * f1;
                this.Frontleftupperarm.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f + 4.0f)) * 0.15f * f1;
                this.Frontrightupperleg.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f + 6.0f)) * 0.15f * f1;
                this.Frontleftupperleg.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f)) * 0.15f * f1;
                this.Backrightupperleg1.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f + 6.0f)) * 0.15f * f1;
                this.Backleftupperleg1.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f + 4.0f)) * 0.15f * f1;
                this.Backrightupperleg2.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f + 2.0f)) * 0.15f * f1;
                this.Backleftupperleg2.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f * 0.5f)) * 0.15f * f1;
            }
            if (!spider.onGround && !this.isRiding) {
                this.Abdoman.rotateAngleX -= MathHelper.cos((float)(f * 0.35f - 1.5f)) * 0.1f * f1 - 0.25f + spider.limbSwingAmount;
                this.Frontrightupperarm.rotateAngleY = 0.5f;
                this.Frontleftupperarm.rotateAngleY = -0.5f;
                this.Frontrightupperleg.rotateAngleY = 1.4f + spider.limbSwingAmount;
                this.Frontleftupperleg.rotateAngleY = -1.4f - spider.limbSwingAmount;
                this.Backrightupperleg1.rotateAngleY = 1.8f + spider.limbSwingAmount;
                this.Backleftupperleg1.rotateAngleY = -1.8f - spider.limbSwingAmount;
                this.Backrightupperleg2.rotateAngleY = 2.0f + spider.limbSwingAmount;
                this.Backleftupperleg2.rotateAngleY = -2.0f - spider.limbSwingAmount;
                this.Frontrightupperleg.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f2 * 0.2f)) * 0.25f;
                this.Frontleftupperleg.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f2 * 0.2f - 0.5f)) * 0.25f;
                this.Backrightupperleg1.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f2 * 0.2f - 1.0f)) * 0.25f;
                this.Backleftupperleg1.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f2 * 0.2f - 1.5f)) * 0.25f;
                this.Backrightupperleg2.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f2 * 0.2f - 2.0f)) * 0.25f;
                this.Backleftupperleg2.rotateAngleX = -1.2217305f + MathHelper.cos((float)(f2 * 0.2f - 2.5f)) * 0.25f;
                if (spider.getAnimID() == 0) {
                    this.Frontrightupperarm.rotateAngleX = -2.0f;
                    this.Frontleftupperarm.rotateAngleX = -2.0f;
                }
            }
            if (spider.getAnimID() == 0) {
                this.Head.rotateAngleX = (0.01f + 0.01f * MathHelper.cos((float)(f2 * 0.1f))) * (float)Math.PI;
                this.Abdoman.rotateAngleX = -((0.01f + 0.01f * MathHelper.cos((float)(f2 * 0.1f))) * (float)Math.PI);
                this.Thorax.rotationPointY = 15.0f - 0.025f * MathHelper.cos((float)(f2 * 0.1f)) * (float)Math.PI;
            }
            if (spider.getAnimID() == 6 && spider.getAnimTick() >= 30 && spider.getAnimTick() < 50) {
                this.Abdoman.rotateAngleX = 0.1f * MathHelper.cos((float)(f2 * 1.0f)) * (float)Math.PI;
            }
            if (spider.getAnimID() == 6 && spider.getAnimTick() >= 50 && spider.getAnimTick() < 100) {
                this.Abdoman.rotateAngleX = 0.1f * MathHelper.cos((float)(f2 * 1.5f)) * (float)Math.PI;
            }
            float faceYaw = f3 * (float)Math.PI / 180.0f;
            float facePitch = f4 * (float)Math.PI / 180.0f;
            this.Head.rotateAngleX += facePitch * 0.9f;
            this.Head.rotateAngleY += faceYaw * 0.9f;
            if (spider.getAnimID() == 1) {
                switch (spider.antiTitanAttackAnimeID) {
                    case 0: {
                        this.animateAntiTitanAttack1();
                        break;
                    }
                    case 1: {
                        this.animateAntiTitanAttack2();
                        break;
                    }
                    case 2: {
                        this.animateAntiTitanAttack3();
                        break;
                    }
                    case 3: {
                        this.animateAntiTitanAttack4();
                    }
                }
            }
            this.animateBirth();
            this.animateBite();
            this.animateSpit();
            this.animateStomp();
            this.animateSwat();
            this.animateShootLightning();
            this.animateShootWeb();
            this.animateStunned();
            this.animateCrush();
        } else {
            this.animateDeath();
        }
    }

    private void animateBite() {
        this.animator.setAnim(4);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -4.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, -16.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateSpit() {
        this.animator.setAnim(2);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.3f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.05f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateStomp() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.3f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.05f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, -0.5f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -2.0f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -2.0f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.2f, 0.2f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.2f, -0.2f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.2f, -0.2f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.4f, -0.3f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.2f, 0.2f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.4f, 0.3f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.2f, 0.75f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.2f, -0.75f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.2f, -0.75f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.2f, 0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSwat() {
        this.animator.setAnim(5);
        this.animator.startPhase(20);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, 0.0f, -1.0f);
        this.animator.rotate(this.Frontrightlowerarm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.4f, -0.5f, 0.1f);
        this.animator.rotate(this.Abdoman, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, 0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Frontrightupperarm, 2.0f, -2.0f, -1.0f);
        this.animator.rotate(this.Frontrightlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.4f, 0.5f, -0.1f);
        this.animator.rotate(this.Abdoman, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.0f, -0.1f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, -0.1f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, -0.1f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, -0.1f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, -0.1f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, -0.1f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, -0.1f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, 12.0f);
        this.animator.rotate(this.Frontleftupperarm, -2.0f, 0.9f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -2.0f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.75f, 0.5f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, -12.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.5f, 0.75f, 1.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.5f, -1.75f, 1.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.25f, -0.5f, -0.5f);
        this.animator.rotate(this.Frontrightlowerarm, 0.25f, 0.5f, 0.5f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, 12.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, -12.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 1.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 1.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.5f, 0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 0.0f, 12.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, -12.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, 12.0f);
        this.animator.rotate(this.Frontleftupperarm, -2.0f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -2.0f, -0.9f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 1.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 1.75f, 0.3f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.75f, -0.5f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Thorax, 0.0f, 0.0f, -12.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.5f, -0.75f, -1.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.5f, 1.75f, -1.0f);
        this.animator.rotate(this.Frontleftlowerarm, -0.5f, 0.5f, -0.5f);
        this.animator.rotate(this.Frontrightlowerarm, -0.5f, -0.5f, 0.5f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateShootWeb() {
        this.animator.setAnim(6);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.3f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.05f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -2.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -4.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, -0.6f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, 0.6f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, -0.3f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.3f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.resetPhase(40);
    }

    private void animateShootLightning() {
        this.animator.setAnim(7);
        this.animator.startPhase(50);
        this.animator.rotate(this.Head, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -1.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -4.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, -0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -4.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -2.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -4.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(50);
    }

    private void animateStunned() {
        this.animator.setAnim(8);
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.1f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -0.75f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.05f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.5f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 6.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.rotate(this.Head, 0.25f, 0.5f, 0.5f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, -0.3f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(300);
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, -0.3f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 6.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, -0.5f, 0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5f, -0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5f, 0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5f, -0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5f, 0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5f, -0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5f, 0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.rotate(this.Head, 0.5f, -0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateCrush() {
        this.animator.setAnim(9);
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.5f, -1.0f, -0.75f);
        this.animator.rotate(this.Frontrightupperarm, 0.5f, 1.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.0f, 0.7f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.0f, -0.7f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.6f, -0.8f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.6f, 0.8f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, 0.5f, 0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5f, 0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, 0.5f, -0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5f, -0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.4f);
        this.animator.rotate(this.Abdoman, 0.25f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.05f, -0.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.05f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.05f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.05f, -0.25f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.05f, -0.25f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.05f, -0.25f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.05f, 0.25f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.05f, 0.25f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.25f, 0.0f, -0.4f);
        this.animator.rotate(this.Abdoman, -0.25f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.3f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 3.5f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.rotate(this.Head, -0.75f, 0.0f, -0.4f);
        this.animator.rotate(this.Abdoman, -0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Thorax, 0.1f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, -1.0f, -6.0f);
        this.animator.rotate(this.Frontleftupperarm, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 0.0f, 0.75f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 0.0f, -0.75f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 0.0f, 0.25f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.4f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.rotate(this.Head, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.Thorax, 0.75f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 6.0f, -12.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.5f, -1.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.5f, 1.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.5f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.5f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.75f, -0.75f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.75f, -0.75f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.75f, 0.5f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.75f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, -0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(70);
        this.animator.rotate(this.Head, 0.0f, 0.0f, -0.75f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, -14.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.3f, -1.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.3f, 1.25f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.3f, 1.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.3f, -1.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.3f, -0.75f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.3f, -0.75f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.3f, 0.5f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.3f, 0.5f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1700);
        this.animator.resetPhase(0);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.5f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 14.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.4f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 15.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(100);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, -0.5f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.25f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, 0.5f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, -0.25f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Abdoman, 0.0f, 0.0f, -0.5f);
        this.animator.move(this.Thorax, 0.0f, 8.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Thorax, 0.0f, 6.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperarm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg1, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightupperleg2, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerarm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontrightlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Frontleftlowerleg, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backleftlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg1, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Backrightlowerleg2, 0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(60);
    }
}

