/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 */
package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelExecutorDragon
extends ModelBase {
    public ModelRenderer body;
    public ModelRenderer bodyscale1;
    public ModelRenderer bodyscale2;
    public ModelRenderer bodyscale3;
    public ModelRenderer rightupperarm;
    public ModelRenderer neck1;
    public ModelRenderer rightwing;
    public ModelRenderer rightfemur;
    public ModelRenderer tail1;
    public ModelRenderer leftwing;
    public ModelRenderer leftupperarm;
    public ModelRenderer leftfemur;
    public ModelRenderer rightlowerarm;
    public ModelRenderer righthand;
    public ModelRenderer neckscale1;
    public ModelRenderer neck2;
    public ModelRenderer neckscale2;
    public ModelRenderer neck3;
    public ModelRenderer neckscale3;
    public ModelRenderer neck4;
    public ModelRenderer neckscale4;
    public ModelRenderer neck5;
    public ModelRenderer neckscale5;
    public ModelRenderer head;
    public ModelRenderer leftheadscale;
    public ModelRenderer rightheadscale;
    public ModelRenderer upperjaw;
    public ModelRenderer lowerjaw;
    public ModelRenderer rightnostril;
    public ModelRenderer leftnostril;
    public ModelRenderer rightwingtip;
    public ModelRenderer rightwingskin;
    public ModelRenderer rightwingtipskin;
    public ModelRenderer rightlowerleg;
    public ModelRenderer rightfoot;
    public ModelRenderer tailscale1;
    public ModelRenderer tail2;
    public ModelRenderer tailscale2;
    public ModelRenderer tail3;
    public ModelRenderer tailscale3;
    public ModelRenderer tail4;
    public ModelRenderer tailscale4;
    public ModelRenderer tail5;
    public ModelRenderer tailscale5;
    public ModelRenderer tail6;
    public ModelRenderer tailscale6;
    public ModelRenderer tail7;
    public ModelRenderer tailscale7;
    public ModelRenderer tail8;
    public ModelRenderer tailscale8;
    public ModelRenderer tail9;
    public ModelRenderer tailscale9;
    public ModelRenderer tail10;
    public ModelRenderer tailscale10;
    public ModelRenderer tail11;
    public ModelRenderer tailscale11;
    public ModelRenderer tail12;
    public ModelRenderer tailscale12;
    public ModelRenderer leftwingtip;
    public ModelRenderer leftwingskin;
    public ModelRenderer leftwingtipskin;
    public ModelRenderer leftlowerarm;
    public ModelRenderer lefthand;
    public ModelRenderer leftlowerleg;
    public ModelRenderer leftfoot;

    public ModelExecutorDragon() {
        this.textureWidth = 256;
        this.textureHeight = 256;
        this.neckscale1 = new ModelRenderer((ModelBase)this, 48, 0);
        this.neckscale1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.neckscale1.addBox(-1.0f, -9.0f, -3.0f, 2, 4, 6, 0.0f);
        this.neck4 = new ModelRenderer((ModelBase)this, 192, 104);
        this.neck4.setRotationPoint(0.0f, 0.0f, -10.0f);
        this.neck4.addBox(-5.0f, -5.0f, -10.0f, 10, 10, 10, 0.0f);
        this.leftfemur = new ModelRenderer((ModelBase)this, 0, 0);
        this.leftfemur.mirror = true;
        this.leftfemur.setRotationPoint(16.0f, 8.0f, 20.0f);
        this.leftfemur.addBox(-8.0f, -4.0f, -8.0f, 16, 32, 16, 0.0f);
        this.setRotateAngle(this.leftfemur, 1.0016445f, 0.0f, 0.0f);
        this.neckscale3 = new ModelRenderer((ModelBase)this, 48, 0);
        this.neckscale3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.neckscale3.addBox(-1.0f, -9.0f, -8.0f, 2, 4, 6, 0.0f);
        this.lefthand = new ModelRenderer((ModelBase)this, 144, 104);
        this.lefthand.mirror = true;
        this.lefthand.setRotationPoint(0.0f, 23.0f, 0.0f);
        this.lefthand.addBox(-4.0f, 0.0f, -12.0f, 8, 4, 16, 0.0f);
        this.setRotateAngle(this.lefthand, 0.75171334f, 0.0f, 0.0f);
        this.leftupperarm = new ModelRenderer((ModelBase)this, 112, 104);
        this.leftupperarm.mirror = true;
        this.leftupperarm.setRotationPoint(8.0f, 8.0f, -18.0f);
        this.leftupperarm.addBox(0.0f, -4.0f, -4.0f, 8, 24, 8, 0.0f);
        this.setRotateAngle(this.leftupperarm, 1.3016665f, 0.0f, 0.0f);
        this.neckscale5 = new ModelRenderer((ModelBase)this, 48, 0);
        this.neckscale5.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.neckscale5.addBox(-1.0f, -9.0f, -8.0f, 2, 4, 6, 0.0f);
        this.tailscale6 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale6.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale6.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.rightupperarm = new ModelRenderer((ModelBase)this, 112, 104);
        this.rightupperarm.setRotationPoint(-8.0f, 8.0f, -18.0f);
        this.rightupperarm.addBox(-8.0f, -4.0f, -4.0f, 8, 24, 8, 0.0f);
        this.setRotateAngle(this.rightupperarm, 1.3016665f, 0.0f, 0.0f);
        this.tailscale11 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale11.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale11.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.tail4 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail4.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail4.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.bodyscale1 = new ModelRenderer((ModelBase)this, 220, 53);
        this.bodyscale1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.bodyscale1.addBox(-1.0f, -18.0f, -26.0f, 2, 6, 12, 0.0f);
        this.tail8 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail8.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail8.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.leftlowerleg = new ModelRenderer((ModelBase)this, 196, 0);
        this.leftlowerleg.mirror = true;
        this.leftlowerleg.setRotationPoint(0.0f, 32.0f, -4.0f);
        this.leftlowerleg.addBox(-6.0f, -2.0f, 0.0f, 12, 32, 12, 0.0f);
        this.setRotateAngle(this.leftlowerleg, 0.5017822f, 0.0f, 0.0f);
        this.leftnostril = new ModelRenderer((ModelBase)this, 112, 0);
        this.leftnostril.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leftnostril.addBox(3.0f, -3.0f, -14.0f, 2, 2, 4, 0.0f);
        this.tail12 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail12.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail12.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.rightwing = new ModelRenderer((ModelBase)this, 112, 88);
        this.rightwing.setRotationPoint(-12.0f, -12.0f, -22.0f);
        this.rightwing.addBox(-56.0f, -4.0f, -4.0f, 56, 8, 8, 0.0f);
        this.tail11 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail11.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail11.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.neck3 = new ModelRenderer((ModelBase)this, 192, 104);
        this.neck3.setRotationPoint(0.0f, 0.0f, -10.0f);
        this.neck3.addBox(-5.0f, -5.0f, -10.0f, 10, 10, 10, 0.0f);
        this.neck1 = new ModelRenderer((ModelBase)this, 192, 104);
        this.neck1.setRotationPoint(0.0f, 4.0f, -36.0f);
        this.neck1.addBox(-5.0f, -5.0f, -5.0f, 10, 10, 10, 0.0f);
        this.bodyscale3 = new ModelRenderer((ModelBase)this, 220, 53);
        this.bodyscale3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.bodyscale3.addBox(-1.0f, -18.0f, 14.0f, 2, 6, 12, 0.0f);
        this.righthand = new ModelRenderer((ModelBase)this, 144, 104);
        this.righthand.setRotationPoint(0.0f, 23.0f, 0.0f);
        this.righthand.addBox(-4.0f, 0.0f, -12.0f, 8, 4, 16, 0.0f);
        this.setRotateAngle(this.righthand, 0.75171334f, 0.0f, 0.0f);
        this.neckscale2 = new ModelRenderer((ModelBase)this, 48, 0);
        this.neckscale2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.neckscale2.addBox(-1.0f, -9.0f, -8.0f, 2, 4, 6, 0.0f);
        this.tailscale2 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale2.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.bodyscale2 = new ModelRenderer((ModelBase)this, 220, 53);
        this.bodyscale2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.bodyscale2.addBox(-1.0f, -18.0f, -6.0f, 2, 6, 12, 0.0f);
        this.tail1 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail1.setRotationPoint(0.0f, 0.0f, 32.0f);
        this.tail1.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.tailscale5 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale5.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale5.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.rightlowerarm = new ModelRenderer((ModelBase)this, 226, 138);
        this.rightlowerarm.setRotationPoint(-4.0f, 20.0f, -1.0f);
        this.rightlowerarm.addBox(-3.0f, -1.0f, -3.0f, 6, 24, 6, 0.0f);
        this.setRotateAngle(this.rightlowerarm, -0.5017822f, 0.0f, 0.0f);
        this.leftwingtipskin = new ModelRenderer((ModelBase)this, -56, 144);
        this.leftwingtipskin.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leftwingtipskin.addBox(-56.0f, 0.0f, 2.0f, 56, 0, 56, 0.0f);
        this.tailscale10 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale10.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale10.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.rightheadscale = new ModelRenderer((ModelBase)this, 0, 0);
        this.rightheadscale.mirror = true;
        this.rightheadscale.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.rightheadscale.addBox(-5.0f, -12.0f, -10.0f, 2, 4, 6, 0.0f);
        this.tail10 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail10.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail10.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.tailscale7 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale7.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale7.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.rightfemur = new ModelRenderer((ModelBase)this, 0, 0);
        this.rightfemur.setRotationPoint(-16.0f, 8.0f, 20.0f);
        this.rightfemur.addBox(-8.0f, -4.0f, -8.0f, 16, 32, 16, 0.0f);
        this.setRotateAngle(this.rightfemur, 1.0016445f, 0.0f, 0.0f);
        this.rightlowerleg = new ModelRenderer((ModelBase)this, 196, 0);
        this.rightlowerleg.setRotationPoint(0.0f, 32.0f, -4.0f);
        this.rightlowerleg.addBox(-6.0f, -2.0f, 0.0f, 12, 32, 12, 0.0f);
        this.setRotateAngle(this.rightlowerleg, 0.5017822f, 0.0f, 0.0f);
        this.upperjaw = new ModelRenderer((ModelBase)this, 176, 44);
        this.upperjaw.setRotationPoint(0.0f, 0.0f, -16.0f);
        this.upperjaw.addBox(-6.0f, -1.0f, -16.0f, 12, 5, 16, 0.0f);
        this.tail7 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail7.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail7.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.leftfoot = new ModelRenderer((ModelBase)this, 112, 0);
        this.leftfoot.mirror = true;
        this.leftfoot.setRotationPoint(0.0f, 31.0f, 4.0f);
        this.leftfoot.addBox(-9.0f, 0.0f, -20.0f, 18, 6, 24, 0.0f);
        this.setRotateAngle(this.leftfoot, 0.75171334f, 0.0f, 0.0f);
        this.head = new ModelRenderer((ModelBase)this, 112, 30);
        this.head.setRotationPoint(0.0f, 0.0f, -10.0f);
        this.head.addBox(-8.0f, -8.0f, -16.0f, 16, 16, 16, 0.0f);
        this.leftwingskin = new ModelRenderer((ModelBase)this, -56, 88);
        this.leftwingskin.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leftwingskin.addBox(-56.0f, 0.0f, 2.0f, 56, 0, 56, 0.0f);
        this.tailscale9 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale9.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale9.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.leftlowerarm = new ModelRenderer((ModelBase)this, 226, 138);
        this.leftlowerarm.mirror = true;
        this.leftlowerarm.setRotationPoint(4.0f, 20.0f, -1.0f);
        this.leftlowerarm.addBox(-3.0f, -1.0f, -3.0f, 6, 24, 6, 0.0f);
        this.setRotateAngle(this.leftlowerarm, -0.5017822f, 0.0f, 0.0f);
        this.leftheadscale = new ModelRenderer((ModelBase)this, 0, 0);
        this.leftheadscale.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leftheadscale.addBox(3.0f, -12.0f, -10.0f, 2, 4, 6, 0.0f);
        this.rightwingtip = new ModelRenderer((ModelBase)this, 112, 136);
        this.rightwingtip.setRotationPoint(-56.0f, 0.0f, 0.0f);
        this.rightwingtip.addBox(-56.0f, -2.0f, -2.0f, 56, 4, 4, 0.0f);
        this.leftwingtip = new ModelRenderer((ModelBase)this, 112, 136);
        this.leftwingtip.mirror = true;
        this.leftwingtip.setRotationPoint(-56.0f, 0.0f, 0.0f);
        this.leftwingtip.addBox(-56.0f, -2.0f, -2.0f, 56, 4, 4, 0.0f);
        this.tailscale8 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale8.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale8.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.tailscale1 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale1.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.tail2 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail2.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail2.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.rightwingtipskin = new ModelRenderer((ModelBase)this, -56, 144);
        this.rightwingtipskin.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.rightwingtipskin.addBox(-56.0f, 0.0f, 2.0f, 56, 0, 56, 0.0f);
        this.neck2 = new ModelRenderer((ModelBase)this, 192, 104);
        this.neck2.setRotationPoint(0.0f, 0.0f, -5.0f);
        this.neck2.addBox(-5.0f, -5.0f, -10.0f, 10, 10, 10, 0.0f);
        this.neck5 = new ModelRenderer((ModelBase)this, 192, 104);
        this.neck5.setRotationPoint(0.0f, 0.0f, -10.0f);
        this.neck5.addBox(-5.0f, -5.0f, -10.0f, 10, 10, 10, 0.0f);
        this.tail9 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail9.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail9.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.rightwingskin = new ModelRenderer((ModelBase)this, -56, 88);
        this.rightwingskin.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.rightwingskin.addBox(-56.0f, 0.0f, 2.0f, 56, 0, 56, 0.0f);
        this.tailscale3 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale3.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.rightnostril = new ModelRenderer((ModelBase)this, 112, 0);
        this.rightnostril.mirror = true;
        this.rightnostril.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.rightnostril.addBox(-5.0f, -3.0f, -14.0f, 2, 2, 4, 0.0f);
        this.tail6 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail6.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail6.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.tail5 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail5.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail5.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.lowerjaw = new ModelRenderer((ModelBase)this, 176, 65);
        this.lowerjaw.setRotationPoint(0.0f, 4.0f, -16.0f);
        this.lowerjaw.addBox(-6.0f, 0.0f, -16.0f, 12, 4, 16, 0.0f);
        this.rightfoot = new ModelRenderer((ModelBase)this, 112, 0);
        this.rightfoot.setRotationPoint(0.0f, 31.0f, 4.0f);
        this.rightfoot.addBox(-9.0f, 0.0f, -20.0f, 18, 6, 24, 0.0f);
        this.setRotateAngle(this.rightfoot, 0.75171334f, 0.0f, 0.0f);
        this.tailscale12 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale12.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale12.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.body = new ModelRenderer((ModelBase)this, 0, 0);
        this.body.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.body.addBox(-12.0f, -12.0f, -32.0f, 24, 24, 64, 0.0f);
        this.tailscale4 = new ModelRenderer((ModelBase)this, 48, 0);
        this.tailscale4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.tailscale4.addBox(-1.0f, -9.0f, 2.0f, 2, 4, 6, 0.0f);
        this.leftwing = new ModelRenderer((ModelBase)this, 112, 88);
        this.leftwing.mirror = true;
        this.leftwing.setRotationPoint(12.0f, -12.0f, -22.0f);
        this.leftwing.addBox(-56.0f, -4.0f, -4.0f, 56, 8, 8, 0.0f);
        this.setRotateAngle(this.leftwing, 0.0f, 0.0f, (float)Math.PI);
        this.tail3 = new ModelRenderer((ModelBase)this, 192, 104);
        this.tail3.setRotationPoint(0.0f, 0.0f, 10.0f);
        this.tail3.addBox(-5.0f, -5.0f, 0.0f, 10, 10, 10, 0.0f);
        this.neckscale4 = new ModelRenderer((ModelBase)this, 48, 0);
        this.neckscale4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.neckscale4.addBox(-1.0f, -9.0f, -8.0f, 2, 4, 6, 0.0f);
        this.neck1.addChild(this.neckscale1);
        this.neck3.addChild(this.neck4);
        this.body.addChild(this.leftfemur);
        this.neck3.addChild(this.neckscale3);
        this.leftlowerarm.addChild(this.lefthand);
        this.body.addChild(this.leftupperarm);
        this.neck5.addChild(this.neckscale5);
        this.tail6.addChild(this.tailscale6);
        this.body.addChild(this.rightupperarm);
        this.tail11.addChild(this.tailscale11);
        this.tail3.addChild(this.tail4);
        this.body.addChild(this.bodyscale1);
        this.tail7.addChild(this.tail8);
        this.leftfemur.addChild(this.leftlowerleg);
        this.upperjaw.addChild(this.leftnostril);
        this.tail11.addChild(this.tail12);
        this.body.addChild(this.rightwing);
        this.tail10.addChild(this.tail11);
        this.neck2.addChild(this.neck3);
        this.body.addChild(this.neck1);
        this.body.addChild(this.bodyscale3);
        this.rightlowerarm.addChild(this.righthand);
        this.neck2.addChild(this.neckscale2);
        this.tail2.addChild(this.tailscale2);
        this.body.addChild(this.bodyscale2);
        this.body.addChild(this.tail1);
        this.tail5.addChild(this.tailscale5);
        this.rightupperarm.addChild(this.rightlowerarm);
        this.leftwingtip.addChild(this.leftwingtipskin);
        this.tail10.addChild(this.tailscale10);
        this.head.addChild(this.rightheadscale);
        this.tail9.addChild(this.tail10);
        this.tail7.addChild(this.tailscale7);
        this.body.addChild(this.rightfemur);
        this.rightfemur.addChild(this.rightlowerleg);
        this.head.addChild(this.upperjaw);
        this.tail6.addChild(this.tail7);
        this.leftlowerleg.addChild(this.leftfoot);
        this.neck5.addChild(this.head);
        this.leftwing.addChild(this.leftwingskin);
        this.tail9.addChild(this.tailscale9);
        this.leftupperarm.addChild(this.leftlowerarm);
        this.head.addChild(this.leftheadscale);
        this.rightwing.addChild(this.rightwingtip);
        this.leftwing.addChild(this.leftwingtip);
        this.tail8.addChild(this.tailscale8);
        this.tail1.addChild(this.tailscale1);
        this.tail1.addChild(this.tail2);
        this.rightwingtip.addChild(this.rightwingtipskin);
        this.neck1.addChild(this.neck2);
        this.neck4.addChild(this.neck5);
        this.tail8.addChild(this.tail9);
        this.rightwing.addChild(this.rightwingskin);
        this.tail3.addChild(this.tailscale3);
        this.upperjaw.addChild(this.rightnostril);
        this.tail5.addChild(this.tail6);
        this.tail4.addChild(this.tail5);
        this.head.addChild(this.lowerjaw);
        this.rightlowerleg.addChild(this.rightfoot);
        this.tail12.addChild(this.tailscale12);
        this.tail4.addChild(this.tailscale4);
        this.body.addChild(this.leftwing);
        this.tail2.addChild(this.tail3);
        this.neck4.addChild(this.neckscale4);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.body.render(f5);
    }

    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }
}

