/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 *  org.lwjgl.opengl.GL11
 */
package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.titan.EntityPigZombieTitan;
import net.minecraft.util.MathHelper;
import org.lwjgl.opengl.GL11;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelPigZombieTitan
extends ModelBase {
    public ModelRenderer Torso;
    public ModelRenderer Hat;
    public ModelRenderer LeftThigh;
    public ModelRenderer RightThigh;
    public ModelRenderer MiddleBody;
    public ModelRenderer TopBody;
    public ModelRenderer Head;
    public ModelRenderer Head2;
    public ModelRenderer LeftShoulder;
    public ModelRenderer RightShoulder;
    public ModelRenderer LeftForearm;
    public ModelRenderer RightForearm;
    public ModelRenderer HeldItem;
    public ModelRenderer LeftCalf;
    public ModelRenderer RightCalf;
    private Animator animator;

    public ModelPigZombieTitan() {
        this(0.0f);
    }

    public ModelPigZombieTitan(float p_i1147_1_) {
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.Hat = new ModelRenderer((ModelBase)this, 32, 0);
        this.Hat.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.Hat.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8, p_i1147_1_ + 0.5f);
        this.LeftShoulder = new ModelRenderer((ModelBase)this, 40, 16);
        this.LeftShoulder.mirror = true;
        this.LeftShoulder.setRotationPoint(6.0f, -2.0f, 0.0f);
        this.LeftShoulder.addBox(-2.0f, -2.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.RightShoulder = new ModelRenderer((ModelBase)this, 40, 16);
        this.RightShoulder.setRotationPoint(-6.0f, -2.0f, 0.0f);
        this.RightShoulder.addBox(-2.0f, -2.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.RightForearm = new ModelRenderer((ModelBase)this, 40, 26);
        this.RightForearm.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.RightForearm.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.TopBody = new ModelRenderer((ModelBase)this, 16, 16);
        this.TopBody.setRotationPoint(0.0f, -4.0f, 0.0f);
        this.TopBody.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.LeftForearm = new ModelRenderer((ModelBase)this, 40, 26);
        this.LeftForearm.mirror = true;
        this.LeftForearm.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.LeftForearm.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.MiddleBody = new ModelRenderer((ModelBase)this, 16, 24);
        this.MiddleBody.setRotationPoint(0.0f, -4.0f, 0.0f);
        this.MiddleBody.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.RightThigh = new ModelRenderer((ModelBase)this, 0, 16);
        this.RightThigh.setRotationPoint(-2.0f, 12.0f, 0.0f);
        this.RightThigh.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.RightCalf = new ModelRenderer((ModelBase)this, 0, 26);
        this.RightCalf.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.RightCalf.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.HeldItem = new ModelRenderer((ModelBase)this, 32, 32);
        this.HeldItem.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.HeldItem.addBox(0.0f, -12.0f, -12.0f, 0, 16, 16, 0.0f);
        this.Torso = new ModelRenderer((ModelBase)this, 16, 32);
        this.Torso.setRotationPoint(0.0f, 12.0f, 0.0f);
        this.Torso.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.LeftThigh = new ModelRenderer((ModelBase)this, 0, 16);
        this.LeftThigh.mirror = true;
        this.LeftThigh.setRotationPoint(2.0f, 12.0f, 0.0f);
        this.LeftThigh.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.LeftCalf = new ModelRenderer((ModelBase)this, 0, 26);
        this.LeftCalf.mirror = true;
        this.LeftCalf.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.LeftCalf.addBox(-2.0f, 0.0f, -2.0f, 4, 6, 4, p_i1147_1_);
        this.RightThigh.addChild(this.RightCalf);
        this.TopBody.addChild(this.LeftShoulder);
        this.TopBody.addChild(this.RightShoulder);
        this.LeftThigh.addChild(this.LeftCalf);
        this.RightShoulder.addChild(this.RightForearm);
        this.MiddleBody.addChild(this.TopBody);
        this.LeftShoulder.addChild(this.LeftForearm);
        this.Torso.addChild(this.MiddleBody);
        this.RightForearm.addChild(this.HeldItem);
        this.Head = new ModelRenderer((ModelBase)this, 0, 0);
        this.Head.setRotationPoint(0.0f, -4.0f, 0.0f);
        this.Head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8, p_i1147_1_);
        this.TopBody.addChild(this.Head);
        this.Head.addChild(this.Hat);
        this.Head2 = new ModelRenderer((ModelBase)this, 0, 0);
        this.Head2.addBox(-4.0f, -10.0f, -4.0f, 8, 8, 8, p_i1147_1_ + 2.0f);
        this.Head.addChild(this.Head2);
        this.animator = new Animator(this);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntityPigZombieTitan entitytitan = (EntityPigZombieTitan)entity;
        this.animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
        this.Head2.isHidden = !entitytitan.isChild();
        if (this.isChild) {
            float f6 = 2.0f;
            GL11.glPushMatrix();
            GL11.glScalef((float)(1.0f / f6), (float)(1.0f / f6), (float)(1.0f / f6));
            GL11.glTranslatef((float)0.0f, (float)(24.0f * f5), (float)0.0f);
            this.RightThigh.render(f5);
            this.Torso.render(f5);
            this.LeftThigh.render(f5);
            GL11.glPopMatrix();
        } else {
            this.RightThigh.render(f5);
            this.Torso.render(f5);
            this.LeftThigh.render(f5);
        }
    }

    public void setAngles() {
        this.LeftShoulder.rotateAngleX = -1.5707964f;
        this.RightShoulder.rotateAngleX = -1.5707964f;
        this.HeldItem.rotateAngleX = 0.7853982f;
        this.RightThigh.rotationPointZ = 0.0f;
        this.LeftThigh.rotationPointZ = 0.0f;
        this.Torso.rotationPointZ = 0.0f;
        this.Torso.rotationPointX = 0.0f;
        this.Torso.rotationPointY = 12.0f;
        this.HeldItem.rotationPointZ = 0.0f;
        this.HeldItem.rotationPointX = 0.0f;
        this.HeldItem.rotationPointY = 4.0f;
        this.RightThigh.rotationPointY = 12.0f;
        this.LeftThigh.rotationPointY = 12.0f;
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntityPigZombieTitan entitytitan = (EntityPigZombieTitan)entity;
        this.animator.update(entity);
        this.setAngles();
        float fo = 0.22206666f;
        if (entitytitan.deathTicks <= 0) {
            float f6 = MathHelper.cos((float)(f2 * 0.1f));
            if (entitytitan.getAnimID() == 0) {
                this.MiddleBody.rotateAngleX = (0.001f + 0.005f * f6) * (float)Math.PI;
                this.TopBody.rotateAngleX = (0.001f + 0.005f * f6) * (float)Math.PI;
                this.Head.rotateAngleX = (0.001f + 0.0075f * f6) * (float)Math.PI;
                this.RightShoulder.rotateAngleY = (-0.001f + 0.01f * f6) * (float)Math.PI;
                this.LeftShoulder.rotateAngleY = (0.001f + -0.01f * f6) * (float)Math.PI;
            }
            if (this.isRiding) {
                this.RightThigh.rotateAngleX = -1.5707964f;
                this.LeftThigh.rotateAngleX = -1.5707964f;
                this.RightThigh.rotateAngleY = 0.31415927f;
                this.LeftThigh.rotateAngleY = -0.31415927f;
                this.RightCalf.rotateAngleX = 1.0471976f;
                this.LeftCalf.rotateAngleX = 1.0471976f;
            } else if (entitytitan.getAnimID() == 0) {
                this.Torso.rotateAngleZ = MathHelper.cos((float)(f * fo)) * 0.1f * f1;
                this.MiddleBody.rotateAngleZ = MathHelper.cos((float)(f * fo - 1.0f)) * 0.1f * f1;
                this.TopBody.rotateAngleZ = MathHelper.cos((float)(f * fo - 2.0f)) * 0.1f * f1;
                this.RightThigh.rotateAngleX = MathHelper.cos((float)(f * fo - 0.5f)) * 1.25f * f1;
                this.LeftThigh.rotateAngleX = MathHelper.cos((float)(f * fo + 2.6415927f)) * 1.25f * f1;
                this.RightCalf.rotateAngleX = MathHelper.cos((float)(f * fo + (float)Math.PI)) * 1.25f * f1;
                this.LeftCalf.rotateAngleX = MathHelper.cos((float)(f * fo)) * 1.25f * f1;
                this.Torso.rotationPointY = 12.0f - MathHelper.cos((float)(f * (fo * 2.0f) + 1.0f)) * 2.0f * f1;
                this.RightThigh.rotationPointY = 12.0f - MathHelper.cos((float)(f * (fo * 2.0f) + 1.0f)) * 2.0f * f1;
                this.LeftThigh.rotationPointY = 12.0f - MathHelper.cos((float)(f * (fo * 2.0f) + 1.0f)) * 2.0f * f1;
                if (this.RightCalf.rotateAngleX < 0.0f) {
                    this.RightCalf.rotateAngleX = 0.0f;
                }
                if (this.LeftCalf.rotateAngleX < 0.0f) {
                    this.LeftCalf.rotateAngleX = 0.0f;
                }
            }
            float faceYaw = f3 * (float)Math.PI / 180.0f;
            float facePitch = f4 * (float)Math.PI / 180.0f;
            if (!entitytitan.onGround && !this.isRiding) {
                this.Torso.rotateAngleZ = 0.0f;
                this.MiddleBody.rotateAngleZ = 0.0f;
                this.TopBody.rotateAngleZ = 0.0f;
                this.Head.rotateAngleZ = 0.0f;
                this.RightShoulder.rotateAngleX -= entitytitan.limbSwingAmount;
                this.LeftShoulder.rotateAngleX -= entitytitan.limbSwingAmount;
                this.Head.rotateAngleX -= entitytitan.limbSwingAmount;
                this.Torso.rotateAngleX += entitytitan.limbSwingAmount;
                this.RightThigh.rotateAngleZ = 0.25f;
                this.LeftThigh.rotateAngleZ = -0.25f;
                this.RightThigh.rotateAngleY = -0.25f;
                this.LeftThigh.rotateAngleY = 0.25f;
                this.RightThigh.rotateAngleX = MathHelper.cos((float)(f2 * 0.2f)) * 0.25f - (float)(entitytitan.motionY / 5.0) + entitytitan.limbSwingAmount;
                this.LeftThigh.rotateAngleX = MathHelper.cos((float)(f2 * 0.2f - (float)Math.PI)) * 0.25f - (float)(entitytitan.motionY / 5.0) + entitytitan.limbSwingAmount;
                this.RightCalf.rotateAngleX = 0.5f - MathHelper.cos((float)(f2 * 0.2f + 0.5f)) * 0.5f;
                this.LeftCalf.rotateAngleX = 0.5f - MathHelper.cos((float)(f2 * 0.2f - 2.6415927f)) * 0.5f;
            }
            if (entitytitan.animID == 0) {
                this.Head.rotateAngleX += facePitch * 0.3f;
                this.Head.rotateAngleY += faceYaw * 0.3f;
                this.TopBody.rotateAngleX += facePitch * 0.3f;
                this.TopBody.rotateAngleY += faceYaw * 0.3f;
                this.MiddleBody.rotateAngleX += facePitch * 0.3f;
                this.MiddleBody.rotateAngleY += faceYaw * 0.3f;
            } else {
                this.Head.rotateAngleX += facePitch * 0.9f;
                this.Head.rotateAngleY += faceYaw * 0.9f;
            }
            if (entitytitan.getAnimID() == 11 && entitytitan.getAnimTick() > 30 && entitytitan.getAnimTick() < 160) {
                this.Head.rotateAngleZ = MathHelper.cos((float)(f2 * 0.25f - 3.0f)) * 0.5f;
                this.TopBody.rotateAngleZ = MathHelper.cos((float)(f2 * 0.25f - 2.0f)) * 0.25f;
                this.MiddleBody.rotateAngleZ = MathHelper.cos((float)(f2 * 0.25f - 1.0f)) * 0.25f;
                this.Torso.rotateAngleZ = MathHelper.cos((float)(f2 * 0.25f)) * 0.25f;
            }
            if (entitytitan.getAnimID() == 12 && entitytitan.getAnimTick() > 30 && entitytitan.getAnimTick() < 50) {
                this.RightForearm.rotateAngleX = 0.1f * MathHelper.cos((float)(f2 * 2.0f)) * (float)Math.PI;
                this.LeftForearm.rotateAngleX = -(0.1f * MathHelper.cos((float)(f2 * 2.0f)) * (float)Math.PI);
            }
            if (entitytitan.getAnimID() == 1) {
                switch (entitytitan.antiTitanAttackAnimeID) {
                    case 0: {
                        this.animateAntiTitanAttack1();
                        break;
                    }
                    case 1: {
                        this.animateAntiTitanAttack2();
                        break;
                    }
                    case 2: {
                        this.animateAntiTitanAttack3();
                        break;
                    }
                    case 3: {
                        this.animateAntiTitanAttack4();
                    }
                }
            }
            this.animateBirth();
            this.animateRoar();
            this.animateRangedAttackThrow();
            this.animateSlam();
            this.animateSwat();
            this.animateSwordDig();
            this.animateLightning();
            this.animateStomp();
            this.animateDownwardSlash();
            this.animateStun();
            this.animateSidewaySlash();
        } else {
            this.animateDeath();
        }
    }

    private void animatePunch() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.rotate(this.TopBody, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.6f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.6f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.2f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Torso, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(30);
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, -1.5f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Torso, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, 3.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, -12.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 1.5f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -1.2f);
        this.animator.rotate(this.RightForearm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 3.0f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, -11.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(8);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(12);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.0f);
        this.animator.rotate(this.RightThigh, 1.8f, -10.0f, 0.5f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftThigh, -0.5f, -10.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 1.75f, -10.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, 0.0f, -12.6f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -12.6f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, -12.6f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 1.5f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Torso, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 2.0f, -1.0f, -1.0f);
        this.animator.rotate(this.LeftForearm, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, -1.5f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.6f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 1.0f);
        this.animator.rotate(this.RightForearm, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 5.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.HeldItem, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 2.0f, -12.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, -12.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, -12.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateSwat() {
        this.animator.setAnim(2);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.0f, 1.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -1.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.75f, 1.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSwordDig() {
        this.animator.setAnim(4);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.2f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.4f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 3.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Head, -1.2f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.5f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(40);
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0f, 3.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Head, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 2.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSlam() {
        this.animator.setAnim(3);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.6f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.6f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, -0.3f, 0.0f, -0.75f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.move(this.Torso, 0.0f, 3.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateLightning() {
        this.animator.setAnim(5);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.35f, 0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.35f, -0.4f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.2f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.35f, 0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.35f, -0.4f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 3.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.9f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -0.9f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.5f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 2.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateStomp() {
        this.animator.setAnim(6);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.2f, 0.75f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.2f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.TopBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, 0.25f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, -0.4f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, -0.75f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, -2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.0f, 0.0f, -0.75f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.TopBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, -0.25f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, 0.4f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateDownwardSlash() {
        this.animator.setAnim(7);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, -0.2f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Torso, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -1.5f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(50);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.5f, -1.5f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateStun() {
        this.animator.setAnim(8);
        this.animator.startPhase(0);
        this.animator.move(this.Torso, 0.0f, 1.0f, -3.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -2.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -3.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 1.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.55f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(40);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(160);
        this.animator.startPhase(40);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.5f, -0.75f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 1.5f, 0.75f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.resetPhase(20);
    }

    private void animateSidewaySlash() {
        this.animator.setAnim(9);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.1f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.25f, 0.5f, -0.5f);
        this.animator.rotate(this.MiddleBody, -0.25f, 0.5f, -0.5f);
        this.animator.rotate(this.Torso, -0.25f, 0.5f, -0.5f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -1.5f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, -0.25f, -0.25f);
        this.animator.rotate(this.MiddleBody, 0.5f, -0.25f, -0.25f);
        this.animator.rotate(this.Torso, 1.0f, -0.25f, -0.5f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, -1.0f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, 0.5f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, -0.5f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -0.5f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -0.5f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 2.0f, 9.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 9.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 9.0f);
        this.animator.rotate(this.RightThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.35f, 0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.35f, -0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.Torso, 0.0f, 10.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 1.4f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 1.4f, 0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.9f, 0.0f);
        this.animator.rotate(this.TopBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, 30.0f);
        this.animator.endPhase();
        this.animator.startPhase(100);
        this.animator.move(this.Torso, 0.0f, 10.0f, 1.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 1.6f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 1.6f, 0.5f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.9f, 0.0f);
        this.animator.rotate(this.TopBody, -0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.3f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftShoulder, -1.3f, 0.0f, 0.5f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, 30.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1700);
        this.animator.resetPhase(0);
    }

    private void animateRoar() {
        this.animator.setAnim(11);
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -1.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(140);
        this.animator.resetPhase(40);
    }

    private void animateRangedAttackThrow() {
        this.animator.setAnim(12);
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Torso, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, -1.5f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.75f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.75f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, 0.8f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, -0.8f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, -0.8f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.8f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.move(this.Torso, 0.0f, 11.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.4f, 1.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.4f, -1.25f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.75f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.75f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.25f, -0.5f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 11.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.4f, 1.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.4f, -1.25f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.75f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.75f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.25f, -0.5f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 2.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, 0.75f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.5f, -0.75f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 5.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 5.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 5.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 1.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.75f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.75f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 3.0f, 6.0f);
        this.animator.move(this.RightThigh, 0.0f, 3.0f, 6.0f);
        this.animator.move(this.LeftThigh, 0.0f, 3.0f, 6.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Torso, 0.0f, 0.0f, -4.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, -4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.RightThigh, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Torso, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Torso, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -1.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Torso, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.25f, 0.25f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, -0.25f);
        this.animator.rotate(this.RightCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftCalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.TopBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.MiddleBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.5f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.5f, -1.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.75f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(80);
        this.animator.resetPhase(40);
    }
}

