/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.titan.EntitySkeletonTitan;
import net.minecraft.util.MathHelper;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelSkeletonTitan
extends ModelBase {
    public ModelRenderer Hips;
    public ModelRenderer LeftThigh;
    public ModelRenderer RightThigh;
    public ModelRenderer Spine1;
    public ModelRenderer Spine2;
    public ModelRenderer Spine3;
    public ModelRenderer Spine4;
    public ModelRenderer Spine5;
    public ModelRenderer Spine6;
    public ModelRenderer Ribs;
    public ModelRenderer Head;
    public ModelRenderer LeftShoulder;
    public ModelRenderer RightShoulder;
    public ModelRenderer LeftForearm;
    public ModelRenderer RightForearm;
    public ModelRenderer HeldItem;
    public ModelRenderer HeldItem2;
    public ModelRenderer LeftFemur;
    public ModelRenderer RightFemur;
    public boolean isWither;
    private Animator animator;

    public ModelSkeletonTitan() {
        this(0.0f);
    }

    public ModelSkeletonTitan(float p_i1147_1_) {
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.RightShoulder = new ModelRenderer((ModelBase)this, 40, 16);
        this.RightShoulder.setRotationPoint(-5.0f, -0.5f, 0.0f);
        this.RightShoulder.addBox(-1.0f, -2.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.RightThigh = new ModelRenderer((ModelBase)this, 0, 16);
        this.RightThigh.setRotationPoint(-2.0f, 12.0f, 0.0f);
        this.RightThigh.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.Spine3 = new ModelRenderer((ModelBase)this, 10, 26);
        this.Spine3.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.Spine3.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.LeftFemur = new ModelRenderer((ModelBase)this, 0, 24);
        this.LeftFemur.mirror = true;
        this.LeftFemur.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.LeftFemur.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.RightForearm = new ModelRenderer((ModelBase)this, 40, 24);
        this.RightForearm.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.RightForearm.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.Spine4 = new ModelRenderer((ModelBase)this, 10, 24);
        this.Spine4.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.Spine4.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.Spine1 = new ModelRenderer((ModelBase)this, 10, 30);
        this.Spine1.setRotationPoint(0.0f, 0.0f, 1.5f);
        this.Spine1.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.Hips = new ModelRenderer((ModelBase)this, 16, 27);
        this.Hips.setRotationPoint(0.0f, 12.0f, 0.0f);
        this.Hips.addBox(-4.0f, -2.0f, -2.0f, 8, 2, 4, p_i1147_1_);
        this.RightFemur = new ModelRenderer((ModelBase)this, 0, 16);
        this.RightFemur.setRotationPoint(0.0f, 6.0f, 0.0f);
        this.RightFemur.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.LeftShoulder = new ModelRenderer((ModelBase)this, 40, 16);
        this.LeftShoulder.mirror = true;
        this.LeftShoulder.setRotationPoint(5.0f, -0.5f, 0.0f);
        this.LeftShoulder.addBox(-1.0f, -2.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.LeftThigh = new ModelRenderer((ModelBase)this, 0, 16);
        this.LeftThigh.mirror = true;
        this.LeftThigh.setRotationPoint(1.9f, 12.0f, 0.1f);
        this.LeftThigh.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.Spine5 = new ModelRenderer((ModelBase)this, 10, 23);
        this.Spine5.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.Spine5.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.Spine6 = new ModelRenderer((ModelBase)this, 10, 22);
        this.Spine6.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.Spine6.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.LeftForearm = new ModelRenderer((ModelBase)this, 40, 24);
        this.LeftForearm.mirror = true;
        this.LeftForearm.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.LeftForearm.addBox(-1.0f, 0.0f, -1.0f, 2, 6, 2, p_i1147_1_);
        this.Spine2 = new ModelRenderer((ModelBase)this, 10, 28);
        this.Spine2.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.Spine2.addBox(-1.0f, -2.0f, 0.0f, 2, 2, 1, p_i1147_1_);
        this.Ribs = new ModelRenderer((ModelBase)this, 16, 16);
        this.Ribs.setRotationPoint(0.0f, 1.0f, -1.5f);
        this.Ribs.addBox(-4.0f, -3.0f, -2.0f, 8, 7, 4, p_i1147_1_);
        this.Head = new ModelRenderer((ModelBase)this, 0, 0);
        this.Head.setRotationPoint(0.0f, -3.0f, 0.0f);
        this.Head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8, p_i1147_1_);
        this.HeldItem = new ModelRenderer((ModelBase)this, 32, -16);
        this.HeldItem.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.HeldItem.addBox(0.0f, -6.0f, -10.0f, 0, 16, 16, 0.0f);
        this.HeldItem2 = new ModelRenderer((ModelBase)this, 32, 17);
        this.HeldItem2.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.HeldItem2.addBox(0.0f, -12.5f, -12.5f, 0, 16, 16, 0.0f);
        this.Ribs.addChild(this.RightShoulder);
        this.Spine2.addChild(this.Spine3);
        this.LeftThigh.addChild(this.LeftFemur);
        this.RightShoulder.addChild(this.RightForearm);
        this.Spine3.addChild(this.Spine4);
        this.Hips.addChild(this.Spine1);
        this.RightThigh.addChild(this.RightFemur);
        this.RightForearm.addChild(this.HeldItem);
        this.RightForearm.addChild(this.HeldItem2);
        this.Ribs.addChild(this.LeftShoulder);
        this.Spine4.addChild(this.Spine5);
        this.Spine5.addChild(this.Spine6);
        this.LeftShoulder.addChild(this.LeftForearm);
        this.Spine1.addChild(this.Spine2);
        this.Spine6.addChild(this.Ribs);
        this.Ribs.addChild(this.Head);
        this.animator = new Animator(this);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntitySkeletonTitan entitytitan = (EntitySkeletonTitan)entity;
        this.animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
        if (entitytitan.getSkeletonType() == 1) {
            this.isWither = true;
            this.HeldItem.isHidden = true;
            this.HeldItem2.isHidden = false;
        } else {
            this.isWither = false;
            this.HeldItem.isHidden = false;
            this.HeldItem2.isHidden = true;
        }
        this.RightThigh.render(f5);
        this.Hips.render(f5);
        this.LeftThigh.render(f5);
    }

    public void setAngles() {
        this.Head.rotationPointX = 0.0f;
        this.Head.rotationPointY = -3.0f;
        this.Head.rotationPointZ = 0.0f;
        this.HeldItem.rotationPointX = 0.0f;
        this.HeldItem.rotationPointY = 4.0f;
        this.HeldItem.rotationPointZ = 0.0f;
        this.HeldItem2.rotationPointZ = 0.0f;
        this.HeldItem2.rotationPointX = 0.0f;
        this.HeldItem2.rotationPointY = 4.0f;
        this.Hips.rotationPointX = 0.0f;
        this.RightThigh.rotationPointX = -2.0f;
        this.LeftThigh.rotationPointX = 2.0f;
        this.Hips.rotationPointZ = 0.0f;
        this.RightThigh.rotationPointZ = 0.0f;
        this.LeftThigh.rotationPointZ = 0.0f;
        this.Hips.rotationPointY = 12.0f;
        this.RightThigh.rotationPointY = 12.0f;
        this.LeftThigh.rotationPointY = 12.0f;
        this.setRotateAngle(this.LeftForearm, -0.17453292f, 0.0f, 0.0f);
        this.setRotateAngle(this.LeftShoulder, 0.08726646f, -0.08726646f, -0.08726646f);
        this.setRotateAngle(this.RightFemur, 0.13962634f, 0.0f, 0.0f);
        this.setRotateAngle(this.RightForearm, -0.17453292f, 0.0f, 0.0f);
        this.setRotateAngle(this.LeftFemur, 0.13962634f, 0.0f, 0.0f);
        this.setRotateAngle(this.LeftThigh, -0.06981317f, -0.06981317f, 0.0f);
        this.setRotateAngle(this.RightThigh, -0.08726646f, 0.06981317f, 0.0f);
        this.setRotateAngle(this.RightShoulder, 0.08726646f, 0.08726646f, 0.08726646f);
        this.setRotateAngle(this.HeldItem, -2.3561945f, 0.0f, 0.0f);
        this.setRotateAngle(this.HeldItem2, 0.7853982f, 0.0f, 0.0f);
    }

    public void setRotateAngle(ModelRenderer modelRenderer, float x, float y, float z) {
        modelRenderer.rotateAngleX = x;
        modelRenderer.rotateAngleY = y;
        modelRenderer.rotateAngleZ = z;
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.animator.update(entity);
        this.setAngles();
        EntitySkeletonTitan entitytitan = (EntitySkeletonTitan)entity;
        float fo = 0.6662f / (entitytitan.getSkeletonType() == 1 ? 2.5f : 4.0f);
        if (entitytitan.deathTicks <= 0) {
            float f6 = MathHelper.cos((float)(f2 * 0.1f));
            if (entitytitan.animID == 0) {
                this.Spine3.rotateAngleX = (0.001f + 0.0025f * f6) * (float)Math.PI;
                this.Spine4.rotateAngleX = (0.001f + 0.0025f * f6) * (float)Math.PI;
                this.Spine5.rotateAngleX = (0.001f + 0.0025f * f6) * (float)Math.PI;
                this.Spine6.rotateAngleX = (0.001f + 0.0025f * f6) * (float)Math.PI;
                this.Head.rotateAngleX = (0.001f + 0.005f * f6) * (float)Math.PI;
                this.RightShoulder.rotateAngleZ = (0.025f + 0.025f * f6) * (float)Math.PI;
                this.LeftShoulder.rotateAngleZ = (-0.025f + -0.025f * f6) * (float)Math.PI;
            }
            if (this.isRiding) {
                this.RightThigh.rotateAngleX = -1.5707964f;
                this.LeftThigh.rotateAngleX = -1.5707964f;
                this.RightThigh.rotateAngleY = 0.31415927f;
                this.LeftThigh.rotateAngleY = -0.31415927f;
                this.RightFemur.rotateAngleX = 1.0471976f;
                this.LeftFemur.rotateAngleX = 1.0471976f;
            } else if (entitytitan.getAnimID() == 0) {
                this.Hips.rotationPointY = 12.0f - MathHelper.cos((float)(f * (fo * 2.0f) + 1.0f)) * 2.0f * f1;
                this.RightThigh.rotationPointY = 12.0f - MathHelper.cos((float)(f * (fo * 2.0f) + 1.0f)) * 2.0f * f1;
                this.LeftThigh.rotationPointY = 12.0f - MathHelper.cos((float)(f * (fo * 2.0f) + 1.0f)) * 2.0f * f1;
                this.Head.rotateAngleZ = MathHelper.cos((float)(f * fo + 3.25f)) * 0.3f * f1;
                this.Spine6.rotateAngleZ = MathHelper.cos((float)(f * fo - 3.0f)) * 0.1f * f1;
                this.Spine5.rotateAngleZ = MathHelper.cos((float)(f * fo - 2.5f)) * 0.1f * f1;
                this.Spine4.rotateAngleZ = MathHelper.cos((float)(f * fo - 2.0f)) * 0.1f * f1;
                this.Spine3.rotateAngleZ = MathHelper.cos((float)(f * fo - 1.5f)) * 0.1f * f1;
                this.Spine2.rotateAngleZ = MathHelper.cos((float)(f * fo - 1.0f)) * 0.1f * f1;
                this.Spine1.rotateAngleZ = MathHelper.cos((float)(f * fo - 0.5f)) * 0.1f * f1;
                this.Hips.rotateAngleZ = MathHelper.cos((float)(f * fo)) * 0.2f * f1;
                this.RightThigh.rotateAngleX = -0.08726646f + MathHelper.cos((float)(f * fo - 0.5f)) * 0.75f * f1;
                this.LeftThigh.rotateAngleX = -0.08726646f + MathHelper.cos((float)(f * fo + 2.6415927f)) * 0.75f * f1;
                this.RightFemur.rotateAngleX = 0.13962634f + MathHelper.cos((float)(f * fo + (float)Math.PI)) * 0.75f * f1;
                this.LeftFemur.rotateAngleX = 0.13962634f + MathHelper.cos((float)(f * fo)) * 0.75f * f1;
                if (this.RightFemur.rotateAngleX < 0.13962634f) {
                    this.RightFemur.rotateAngleX = 0.13962634f;
                }
                if (this.LeftFemur.rotateAngleX < 0.13962634f) {
                    this.LeftFemur.rotateAngleX = 0.13962634f;
                }
                if (!this.isRiding) {
                    this.RightShoulder.rotateAngleX = 0.08726646f + MathHelper.cos((float)(f * fo + (float)Math.PI)) * 1.0f * f1;
                    this.LeftShoulder.rotateAngleX = 0.08726646f + MathHelper.cos((float)(f * fo)) * 1.0f * f1;
                    this.RightForearm.rotateAngleX = -0.17453292f + MathHelper.cos((float)(f * fo + 2.1415927f)) * 1.0f * f1;
                    this.LeftForearm.rotateAngleX = -0.17453292f + MathHelper.cos((float)(f * fo - 1.0f)) * 1.0f * f1;
                    if (this.RightForearm.rotateAngleX > -0.17453292f) {
                        this.RightForearm.rotateAngleX = -0.17453292f;
                    }
                    if (this.LeftForearm.rotateAngleX > -0.17453292f) {
                        this.LeftForearm.rotateAngleX = -0.17453292f;
                    }
                }
            }
            float faceYaw = f3 * (float)Math.PI / 180.0f;
            float facePitch = f4 * (float)Math.PI / 180.0f;
            if (entitytitan.animID == 0) {
                this.Head.rotateAngleX += facePitch * 0.5f;
                this.Head.rotateAngleY += faceYaw * 0.5f;
                this.Spine6.rotateAngleX += facePitch * 0.1f;
                this.Spine6.rotateAngleY += faceYaw * 0.1f;
                this.Spine5.rotateAngleX += facePitch * 0.1f;
                this.Spine5.rotateAngleY += faceYaw * 0.1f;
                this.Spine4.rotateAngleX += facePitch * 0.1f;
                this.Spine4.rotateAngleY += faceYaw * 0.1f;
                this.Spine3.rotateAngleX += facePitch * 0.1f;
                this.Spine3.rotateAngleY += faceYaw * 0.1f;
                this.RightShoulder.rotateAngleX -= facePitch * 0.4f;
                this.LeftShoulder.rotateAngleX -= facePitch * 0.4f;
            } else {
                this.Head.rotateAngleX += facePitch * 0.9f;
                this.Head.rotateAngleY += faceYaw * 0.9f;
            }
            if (!entitytitan.onGround && !this.isRiding) {
                this.Spine6.rotateAngleZ = 0.0f;
                this.Spine5.rotateAngleZ = 0.0f;
                this.Spine4.rotateAngleZ = 0.0f;
                this.Spine3.rotateAngleZ = 0.0f;
                this.Spine2.rotateAngleZ = 0.0f;
                this.Spine1.rotateAngleZ = 0.0f;
                this.Hips.rotateAngleZ = 0.0f;
                this.Head.rotateAngleZ = 0.0f;
                this.RightShoulder.rotateAngleX = -entitytitan.limbSwingAmount;
                this.LeftShoulder.rotateAngleX = -entitytitan.limbSwingAmount;
                this.RightForearm.rotateAngleX = -(entitytitan.limbSwingAmount / 2.0f);
                this.LeftForearm.rotateAngleX = -(entitytitan.limbSwingAmount / 2.0f);
                this.Head.rotateAngleX -= entitytitan.limbSwingAmount;
                this.Hips.rotateAngleX += entitytitan.limbSwingAmount;
                this.RightThigh.rotateAngleZ = 0.25f;
                this.LeftThigh.rotateAngleZ = -0.25f;
                this.RightThigh.rotateAngleY = -0.25f;
                this.LeftThigh.rotateAngleY = 0.25f;
                this.RightThigh.rotateAngleX = MathHelper.cos((float)(f2 * 0.2f)) * 0.25f - (float)(entitytitan.motionY / 5.0) + entitytitan.limbSwingAmount;
                this.LeftThigh.rotateAngleX = MathHelper.cos((float)(f2 * 0.2f - (float)Math.PI)) * 0.25f - (float)(entitytitan.motionY / 5.0) + entitytitan.limbSwingAmount;
                this.RightFemur.rotateAngleX = 0.5f - MathHelper.cos((float)(f2 * 0.2f + 0.5f)) * 0.5f;
                this.LeftFemur.rotateAngleX = 0.5f - MathHelper.cos((float)(f2 * 0.2f - 2.6415927f)) * 0.5f;
            }
            if (entitytitan.getAnimID() == 5 && entitytitan.getAnimTick() > 100 && entitytitan.getAnimTick() < 300) {
                this.LeftForearm.rotateAngleX = -MathHelper.cos((float)(f2 * 4.0f)) * 0.5f;
            }
            if (entitytitan.getAnimID() == 1) {
                switch (entitytitan.antiTitanAttackAnimeID) {
                    case 0: {
                        this.animateAntiTitanAttack1();
                        break;
                    }
                    case 1: {
                        this.animateAntiTitanAttack2();
                        break;
                    }
                    case 2: {
                        this.animateAntiTitanAttack3();
                        break;
                    }
                    case 3: {
                        this.animateAntiTitanAttack4();
                    }
                }
            }
            this.animatePunch();
            this.animateBackhand();
            this.animateSwat();
            this.animateShot();
            this.animateStomp();
            this.animateDownwardSlash();
            this.animateStun();
            this.animateLightning();
            this.animateGiantShot();
            this.animateLightningHand();
            this.animateBirth();
        } else {
            this.animateDeath();
        }
    }

    private void animateStun() {
        this.animator.setAnim(8);
        this.animator.startPhase(0);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -3.0f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Hips, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.6f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.8f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.6f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.6f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.3f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.3f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(200);
        this.animator.startPhase(70);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.8f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.6f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.6f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.3f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.3f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.8f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -4.0f, -0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -4.0f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.2f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -0.2f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, -20.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -20.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, -20.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, -0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.3f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 2.0f);
        this.animator.rotate(this.RightThigh, -0.9f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.9f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 2.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 2.0f);
        this.animator.rotate(this.RightThigh, -0.9f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.9f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateSwat() {
        this.animator.setAnim(2);
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, 0.75f, 1.5f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, -1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 6.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, -1.25f, -1.5f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.375f, 1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateBackhand() {
        this.animator.setAnim(4);
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -2.5f, -0.75f, -1.5f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 6.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -1.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.5f, 0.75f, 1.5f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.375f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.375f, -1.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animatePunch() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.6f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.6f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.2f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Ribs, 0.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateLightning() {
        this.animator.setAnim(9);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.6f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.35f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.6f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.35f, 0.25f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0f, -0.6f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.6f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.25f, 0.0f);
        this.animator.rotate(this.HeldItem2, -1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.6f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.6f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.35f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.6f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.35f, 0.25f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.9f, 0.0f, 1.0f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 1.0f);
        this.animator.rotate(this.HeldItem2, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.HeldItem, 0.0f, 100.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -8.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -2.0f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 2.0f, 10.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 100.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.25f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.25f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 4.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, -8.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.6f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 4.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 4.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.5f, -1.5f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine2, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine1, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.5f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, -8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, -8.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine5, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine4, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine3, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine2, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Spine1, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(8);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(12);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.0f);
        this.animator.rotate(this.RightThigh, 1.8f, -10.0f, 0.5f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.5f);
        this.animator.rotate(this.LeftThigh, -0.5f, -10.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 1.75f, -10.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, 0.0f, -12.6f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, -12.6f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, -12.6f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(0);
    }

    private void animateShot() {
        this.animator.setAnim(5);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.2f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -0.4f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(300);
        this.animator.resetPhase(30);
    }

    private void animateStomp() {
        this.animator.setAnim(6);
        this.animator.startPhase(25);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -2.6f, 0.2f, 0.75f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.2f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.5f, 0.0f, -0.5f);
        this.animator.rotate(this.LeftFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.8f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, -0.8f);
        this.animator.rotate(this.RightShoulder, 0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, -2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.6f, 0.0f, -0.75f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.Spine6, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, -0.8f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.8f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.Hips, 0.0f, 2.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 0.0f);
        this.animator.rotate(this.RightThigh, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.8f);
        this.animator.rotate(this.RightShoulder, 0.75f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.75f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.5f, 0.75f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateDownwardSlash() {
        this.animator.setAnim(7);
        this.animator.startPhase(60);
        this.animator.move(this.HeldItem, 0.0f, 2.0f, -6.0f);
        this.animator.move(this.Hips, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.Hips, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.HeldItem2, 0.5f, 0.5f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(30);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -3.0f, 0.0f, -0.875f);
        this.animator.rotate(this.LeftShoulder, 1.0f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(50);
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, -5.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -5.5f);
        this.animator.rotate(this.RightThigh, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, -0.125f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightShoulder, -3.0f, 0.0f, -0.75f);
        this.animator.rotate(this.LeftShoulder, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 50.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 3.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 5.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 5.5f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 5.5f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 6.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 6.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 6.0f);
        this.animator.rotate(this.RightThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0707964f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0707964f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 12.0f);
        this.animator.rotate(this.RightThigh, -0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.65f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.6f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.0707964f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, -1.0707964f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.RightThigh, 0.0f, 2.0f, 12.0f);
        this.animator.move(this.LeftThigh, 0.0f, 2.0f, 12.0f);
        this.animator.rotate(this.RightThigh, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.5f, 0.5f);
        this.animator.rotate(this.Spine6, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.25f, -0.4f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.25f, 0.4f, 0.0f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 2.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.Hips, 0.0f, 10.0f, -3.0f);
        this.animator.move(this.Head, 0.0f, -12.0f, 2.5f);
        this.animator.move(this.RightThigh, 0.0f, 11.0f, 0.0f);
        this.animator.move(this.LeftThigh, 10.0f, 11.0f, 12.0f);
        this.animator.rotate(this.RightThigh, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 1.5f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 14.4f, 14.4f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.5f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -3.0f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 1.0f, 10.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, -10.0f);
        this.animator.move(this.HeldItem2, 0.0f, 0.0f, -10.0f);
        this.animator.endPhase();
        this.animator.startPhase(100);
        this.animator.move(this.Hips, 0.0f, 10.0f, -3.0f);
        this.animator.move(this.Head, 0.0f, -12.0f, -1.0f);
        this.animator.move(this.RightThigh, 0.0f, 11.0f, 0.0f);
        this.animator.move(this.LeftThigh, 10.0f, 11.0f, 12.0f);
        this.animator.rotate(this.RightThigh, 1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, 0.0f, 0.0f, 1.5f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 14.4f, 14.4f, 0.0f);
        this.animator.rotate(this.Spine6, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 1.75f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -3.0f, 0.0f, 0.75f);
        this.animator.rotate(this.RightForearm, 0.15f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.15f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 2.0f, 1.0f, 10.0f);
        this.animator.move(this.HeldItem, 0.0f, 0.0f, -10.0f);
        this.animator.move(this.HeldItem2, 0.0f, 0.0f, -10.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1700);
        this.animator.resetPhase(0);
    }

    private void animateGiantShot() {
        this.animator.setAnim(11);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.2f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -0.4f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(50);
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.6f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.Hips, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, 0.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, 0.0f);
        this.animator.rotate(this.RightThigh, -0.45f, 0.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.45f, -0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.9f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.35f, 0.5f, -1.5f);
        this.animator.rotate(this.LeftShoulder, -1.2f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -0.5f, 0.0f, -0.3f);
        this.animator.rotate(this.LeftForearm, -0.4f, 0.0f, 1.5f);
        this.animator.rotate(this.HeldItem, 1.0f, 2.5f, 1.0f);
        this.animator.rotate(this.Spine1, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(20);
    }

    private void animateLightningHand() {
        this.animator.setAnim(12);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.5f, 0.5f);
        this.animator.rotate(this.LeftShoulder, 0.8f, -0.5f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.8f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, 0.8f, 0.0f, -0.75f);
        this.animator.rotate(this.RightForearm, -1.6f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.6f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.RightThigh, 2.0f, 0.0f, 2.0f);
        this.animator.move(this.LeftThigh, -2.0f, 0.0f, -2.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 1.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -1.8f, 0.0f);
        this.animator.rotate(this.RightForearm, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 1.8f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, -1.8f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(2);
        this.animator.move(this.RightThigh, 2.0f, 0.0f, 2.0f);
        this.animator.move(this.LeftThigh, -2.0f, 0.0f, -2.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 1.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -2.0f, -1.8f, 0.0f);
        this.animator.rotate(this.RightForearm, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 1.8f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, -1.8f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(8);
        this.animator.move(this.RightThigh, 2.0f, 0.0f, 2.0f);
        this.animator.move(this.LeftThigh, -2.0f, 0.0f, -2.0f);
        this.animator.rotate(this.RightThigh, -0.25f, 1.5f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, -1.0f, -1.8f, 0.0f);
        this.animator.rotate(this.RightForearm, -2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 1.8f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, -1.8f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(10);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.4f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.55f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.1f, 0.0f, 0.25f);
        this.animator.rotate(this.LeftShoulder, 0.1f, 0.0f, -0.25f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(160);
        this.animator.startPhase(60);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 9.5f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.5f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.55f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.1f, 0.0f, 0.25f);
        this.animator.rotate(this.LeftShoulder, 2.5f, 2.5f, 0.25f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.HeldItem, 0.0f, 10.0f, 0.0f);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.4f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, -1.55f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.1f, 0.0f, 0.25f);
        this.animator.rotate(this.LeftShoulder, 2.5f, 1.5f, 0.2f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.HeldItem2, 1.6f, 1.6f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(40);
        this.animator.startPhase(60);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.9f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 1.5f, 0.75f, 0.25f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -1.9f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -1.9f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(120);
        this.animator.move(this.Hips, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.RightThigh, 0.0f, 10.0f, 8.0f);
        this.animator.move(this.LeftThigh, 0.0f, 10.0f, 8.0f);
        this.animator.rotate(this.RightThigh, -2.0f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -2.0f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine5, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine4, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine3, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine2, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Spine1, -0.125f, 0.125f, 0.0f);
        this.animator.rotate(this.Hips, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, -1.5f, 0.0f, 0.75f);
        this.animator.rotate(this.LeftShoulder, -0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.RightForearm, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.75f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 4.0f, 3.0f);
        this.animator.move(this.RightThigh, 0.0f, 4.0f, 3.0f);
        this.animator.move(this.LeftThigh, 0.0f, 4.0f, 3.0f);
        this.animator.rotate(this.RightThigh, -1.25f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.Hips, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.RightThigh, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.LeftThigh, 0.0f, 1.0f, -2.0f);
        this.animator.rotate(this.RightThigh, 0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.25f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Hips, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftShoulder, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.RightForearm, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftForearm, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.RightThigh, -0.125f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.125f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine6, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.125f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.125f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.125f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.125f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.startPhase(10);
        this.animator.rotate(this.RightThigh, -0.125f, 0.25f, 0.0f);
        this.animator.rotate(this.LeftThigh, -0.125f, -0.25f, 0.0f);
        this.animator.rotate(this.RightFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.LeftFemur, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.3f, -0.5f, 0.0f);
        this.animator.rotate(this.Spine6, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine5, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine4, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine3, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine2, 0.05f, 0.0f, 0.0f);
        this.animator.rotate(this.Spine1, 0.05f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(10);
        this.animator.resetPhase(40);
    }
}

