/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.client.model.ModelBase
 *  net.minecraft.client.model.ModelRenderer
 *  net.minecraft.entity.Entity
 *  net.minecraft.util.MathHelper
 */
package net.minecraft.theTitans.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.entity.titan.EntityCreeperTitan;
import net.minecraft.util.MathHelper;
import thehippomaster.AnimationAPI.IAnimatedEntity;
import thehippomaster.AnimationAPI.client.Animator;

public class ModelCreeperTitan
extends ModelBase {
    public ModelRenderer BottomBody;
    public ModelRenderer Rightfrontupperleg;
    public ModelRenderer Rightbackupperleg;
    public ModelRenderer Leftfrontupperleg;
    public ModelRenderer Leftbackupperleg;
    public ModelRenderer BottomMiddle;
    public ModelRenderer BottomTop;
    public ModelRenderer Head;
    public ModelRenderer Rightfrontcalf;
    public ModelRenderer Rightfrontfoot;
    public ModelRenderer Rightbackcalf;
    public ModelRenderer Rightbackfoot;
    public ModelRenderer Leftfrontcalf;
    public ModelRenderer Leftfrontfoot;
    public ModelRenderer Leftbackcalf;
    public ModelRenderer Leftbackfoot;
    private Animator animator;

    public ModelCreeperTitan() {
        this(0.0f);
    }

    public ModelCreeperTitan(float p_i1147_1_) {
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.Leftbackfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.Leftbackfoot.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Leftbackfoot.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Leftfrontupperleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.Leftfrontupperleg.setRotationPoint(3.0f, 16.0f, -1.0f);
        this.Leftfrontupperleg.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Rightbackcalf = new ModelRenderer((ModelBase)this, 0, 16);
        this.Rightbackcalf.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Rightbackcalf.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Rightbackupperleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.Rightbackupperleg.setRotationPoint(-3.0f, 16.0f, 1.0f);
        this.Rightbackupperleg.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Leftfrontcalf = new ModelRenderer((ModelBase)this, 0, 16);
        this.Leftfrontcalf.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Leftfrontcalf.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.BottomTop = new ModelRenderer((ModelBase)this, 16, 16);
        this.BottomTop.setRotationPoint(0.0f, -4.0f, 0.0f);
        this.BottomTop.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.Head = new ModelRenderer((ModelBase)this, 0, 0);
        this.Head.setRotationPoint(0.0f, -4.0f, 0.0f);
        this.Head.addBox(-4.0f, -8.0f, -4.0f, 8, 8, 8, p_i1147_1_);
        this.BottomBody = new ModelRenderer((ModelBase)this, 16, 32);
        this.BottomBody.setRotationPoint(0.0f, 16.0f, 0.0f);
        this.BottomBody.addBox(-4.0f, -2.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.Leftbackcalf = new ModelRenderer((ModelBase)this, 0, 16);
        this.Leftbackcalf.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Leftbackcalf.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Leftbackupperleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.Leftbackupperleg.setRotationPoint(3.0f, 16.0f, 1.0f);
        this.Leftbackupperleg.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Rightbackfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.Rightbackfoot.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Rightbackfoot.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Rightfrontupperleg = new ModelRenderer((ModelBase)this, 0, 16);
        this.Rightfrontupperleg.setRotationPoint(-3.0f, 16.0f, -1.0f);
        this.Rightfrontupperleg.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.BottomMiddle = new ModelRenderer((ModelBase)this, 16, 24);
        this.BottomMiddle.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.BottomMiddle.addBox(-4.0f, -4.0f, -2.0f, 8, 4, 4, p_i1147_1_);
        this.Leftfrontfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.Leftfrontfoot.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Leftfrontfoot.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Rightfrontcalf = new ModelRenderer((ModelBase)this, 0, 16);
        this.Rightfrontcalf.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Rightfrontcalf.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Rightfrontfoot = new ModelRenderer((ModelBase)this, 0, 24);
        this.Rightfrontfoot.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.Rightfrontfoot.addBox(-2.0f, 0.0f, -2.0f, 4, 4, 4, p_i1147_1_);
        this.Leftbackcalf.addChild(this.Leftbackfoot);
        this.Rightbackupperleg.addChild(this.Rightbackcalf);
        this.Leftfrontupperleg.addChild(this.Leftfrontcalf);
        this.BottomMiddle.addChild(this.BottomTop);
        this.BottomTop.addChild(this.Head);
        this.Leftbackupperleg.addChild(this.Leftbackcalf);
        this.Rightbackcalf.addChild(this.Rightbackfoot);
        this.BottomBody.addChild(this.BottomMiddle);
        this.Leftfrontcalf.addChild(this.Leftfrontfoot);
        this.Rightfrontupperleg.addChild(this.Rightfrontcalf);
        this.Rightfrontcalf.addChild(this.Rightfrontfoot);
        this.animator = new Animator(this);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.animate((IAnimatedEntity)entity, f, f1, f2, f3, f4, f5);
        this.Leftfrontupperleg.render(f5);
        this.Rightbackupperleg.render(f5);
        this.BottomBody.render(f5);
        this.Leftbackupperleg.render(f5);
        this.Rightfrontupperleg.render(f5);
    }

    public void setAngles() {
        float f = 16.1f;
        this.Rightbackupperleg.setRotationPoint(-3.0f, f, 1.0f);
        this.Leftfrontupperleg.setRotationPoint(3.0f, f, -1.0f);
        this.BottomBody.setRotationPoint(0.0f, f, 0.0f);
        this.Leftbackupperleg.setRotationPoint(3.0f, f, 1.0f);
        this.Rightfrontupperleg.setRotationPoint(-3.0f, f, -1.0f);
        this.Rightbackcalf.rotateAngleX = 0.7853982f;
        this.Leftfrontcalf.rotateAngleX = 0.7853982f;
        this.Leftbackcalf.rotateAngleX = 0.7853982f;
        this.Rightfrontcalf.rotateAngleX = 0.7853982f;
        this.Rightbackfoot.rotateAngleX = 0.5235988f;
        this.Leftfrontfoot.rotateAngleX = 0.5235988f;
        this.Rightfrontfoot.rotateAngleX = 0.5235988f;
        this.Leftbackfoot.rotateAngleX = 0.5235988f;
        this.Leftfrontupperleg.rotateAngleX = -1.3089969f;
        this.Leftfrontupperleg.rotateAngleY = -0.525f;
        this.Rightbackupperleg.rotateAngleY = 2.625f;
        this.Rightbackupperleg.rotateAngleX = -1.3089969f;
        this.Leftbackupperleg.rotateAngleY = -2.625f;
        this.Leftbackupperleg.rotateAngleX = -1.3089969f;
        this.Rightfrontupperleg.rotateAngleX = -1.3089969f;
        this.Rightfrontupperleg.rotateAngleY = 0.525f;
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        this.animator.update(entity);
        this.setAngles();
        EntityCreeperTitan entitytitan = (EntityCreeperTitan)entity;
        float f6 = MathHelper.cos((float)(f2 * 0.1f));
        if (entitytitan.deathTicks <= 0) {
            float faceYaw = f3 * (float)Math.PI / 180.0f;
            float facePitch = f4 * (float)Math.PI / 180.0f;
            this.BottomBody.rotateAngleZ = MathHelper.cos((float)(f * 0.25f)) * 0.3f * f1;
            this.BottomMiddle.rotateAngleZ = MathHelper.cos((float)(f * 0.25f - 1.0f)) * 0.3f * f1;
            this.BottomTop.rotateAngleZ = MathHelper.cos((float)(f * 0.25f - 2.0f)) * 0.3f * f1;
            this.Head.rotateAngleZ = MathHelper.cos((float)(f * 0.25f - 3.0f)) * 0.3f * f1;
            if (entitytitan.getAnimID() == 8 && entitytitan.getAnimTick() > 130 && entitytitan.getAnimTick() < 430) {
                this.BottomMiddle.rotateAngleY = MathHelper.cos((float)(f2 * 0.05f + 2.0f)) * 0.2f;
                this.BottomTop.rotateAngleY = MathHelper.cos((float)(f2 * 0.05f + 1.0f)) * 0.2f;
                this.Head.rotateAngleY = MathHelper.cos((float)(f2 * 0.05f)) * 0.2f;
                this.BottomMiddle.rotateAngleX = (-0.025f + -0.0125f * MathHelper.cos((float)(f2 * 0.1f - 2.0f))) * (float)Math.PI;
                this.BottomTop.rotateAngleX = (0.0125f + 0.0125f * MathHelper.cos((float)(f2 * 0.1f - 1.0f))) * (float)Math.PI;
                this.Head.rotateAngleX = (0.0125f + 0.0125f * f6) * (float)Math.PI;
            }
            if (entitytitan.getAnimID() == 13 && entitytitan.getAnimTick() < 5) {
                this.BottomMiddle.rotateAngleX = (-0.005f + -0.005f * MathHelper.cos((float)(f2 * 0.1f - 2.0f))) * (float)Math.PI;
                this.BottomTop.rotateAngleX = (0.005f + 0.005f * MathHelper.cos((float)(f2 * 0.1f - 1.0f))) * (float)Math.PI;
                this.Head.rotateAngleX = (0.005f + 0.005f * f6) * (float)Math.PI;
            }
            if (this.isRiding) {
                this.Rightbackupperleg.setRotationPoint(-3.0f, 21.0f, 1.0f);
                this.Leftfrontupperleg.setRotationPoint(3.0f, 21.0f, -1.0f);
                this.BottomBody.setRotationPoint(0.0f, 21.0f, 0.0f);
                this.Leftbackupperleg.setRotationPoint(3.0f, 21.0f, 1.0f);
                this.Rightfrontupperleg.setRotationPoint(-3.0f, 21.0f, -1.0f);
                this.Leftfrontupperleg.rotateAngleX = -1.6f;
                this.Leftbackupperleg.rotateAngleX = -1.6f;
                this.Rightfrontupperleg.rotateAngleX = -1.6f;
                this.Rightbackupperleg.rotateAngleX = -1.6f;
                this.Leftfrontupperleg.rotateAngleY = -0.725f;
                this.Leftbackupperleg.rotateAngleY = -2.25f;
                this.Rightfrontupperleg.rotateAngleY = 0.725f;
                this.Rightbackupperleg.rotateAngleY = 2.25f;
                this.Leftbackcalf.rotateAngleX = 1.0f;
                this.Leftfrontcalf.rotateAngleX = 1.0f;
                this.Rightbackcalf.rotateAngleX = 1.0f;
                this.Rightfrontcalf.rotateAngleX = 1.0f;
            } else if (entitytitan.getAnimID() == 0) {
                this.BottomMiddle.rotateAngleX = (-0.025f + -0.0125f * MathHelper.cos((float)(f2 * 0.1f - 2.0f))) * (float)Math.PI;
                this.BottomTop.rotateAngleX = (0.0125f + 0.0125f * MathHelper.cos((float)(f2 * 0.1f - 1.0f))) * (float)Math.PI;
                this.Head.rotateAngleX = (0.0125f + 0.0125f * f6) * (float)Math.PI;
                this.Leftfrontupperleg.rotateAngleX = -1.3089969f + MathHelper.cos((float)(f * 0.25f + 0.25f)) * 0.75f * f1;
                this.Leftbackupperleg.rotateAngleX = -1.3089969f + MathHelper.cos((float)(f * 0.25f + 3.3915927f)) * 0.75f * f1;
                this.Rightfrontupperleg.rotateAngleX = -1.3089969f + MathHelper.cos((float)(f * 0.25f + 3.3915927f)) * 0.75f * f1;
                this.Rightbackupperleg.rotateAngleX = -1.3089969f + MathHelper.cos((float)(f * 0.25f + 0.25f)) * 0.75f * f1;
                this.Leftfrontupperleg.rotateAngleY = -0.525f + MathHelper.cos((float)(f * 0.25f + 2.6415927f)) * 0.5f * f1;
                this.Leftbackupperleg.rotateAngleY = -2.625f + MathHelper.cos((float)(f * 0.25f - 0.5f)) * 0.5f * f1;
                this.Rightfrontupperleg.rotateAngleY = 0.525f - MathHelper.cos((float)(f * 0.25f - 0.75f)) * 0.5f * f1;
                this.Rightbackupperleg.rotateAngleY = 2.625f - MathHelper.cos((float)(f * 0.25f + 2.6415927f)) * 0.5f * f1;
                this.Leftbackcalf.rotateAngleX = 0.7853982f + MathHelper.cos((float)(f * 0.25f)) * 0.5f * f1;
                this.Leftfrontcalf.rotateAngleX = 0.7853982f + MathHelper.cos((float)(f * 0.25f + (float)Math.PI)) * 0.5f * f1;
                this.Rightbackcalf.rotateAngleX = 0.7853982f + MathHelper.cos((float)(f * 0.25f + (float)Math.PI)) * 0.5f * f1;
                this.Rightfrontcalf.rotateAngleX = 0.7853982f + MathHelper.cos((float)(f * 0.25f)) * 0.5f * f1;
                if (this.Leftfrontupperleg.rotateAngleX > -1.3089969f) {
                    this.Leftfrontupperleg.rotateAngleX = -1.3089969f;
                }
                if (this.Rightfrontupperleg.rotateAngleX > -1.3089969f) {
                    this.Rightfrontupperleg.rotateAngleX = -1.3089969f;
                }
                if (this.Rightbackupperleg.rotateAngleX > -1.3089969f) {
                    this.Rightbackupperleg.rotateAngleX = -1.3089969f;
                }
                if (this.Leftbackupperleg.rotateAngleX > -1.3089969f) {
                    this.Leftbackupperleg.rotateAngleX = -1.3089969f;
                }
                if (this.Rightbackcalf.rotateAngleX < 0.7853982f) {
                    this.Rightbackcalf.rotateAngleX = 0.7853982f;
                }
                if (this.Rightfrontcalf.rotateAngleX < 0.7853982f) {
                    this.Rightfrontcalf.rotateAngleX = 0.7853982f;
                }
                if (this.Leftbackcalf.rotateAngleX < 0.7853982f) {
                    this.Leftbackcalf.rotateAngleX = 0.7853982f;
                }
                if (this.Leftfrontcalf.rotateAngleX < 0.7853982f) {
                    this.Leftfrontcalf.rotateAngleX = 0.7853982f;
                }
                if (this.Rightbackcalf.rotateAngleX < 0.7853982f) {
                    this.Rightbackcalf.rotateAngleX = 0.7853982f;
                }
                if (this.Rightfrontcalf.rotateAngleX < 0.7853982f) {
                    this.Rightfrontcalf.rotateAngleX = 0.7853982f;
                }
            }
            this.Head.rotateAngleX += facePitch * 0.3f;
            this.Head.rotateAngleY += faceYaw * 0.3f;
            this.BottomTop.rotateAngleX += facePitch * 0.3f;
            this.BottomTop.rotateAngleY += faceYaw * 0.3f;
            this.BottomMiddle.rotateAngleX += facePitch * 0.3f;
            this.BottomMiddle.rotateAngleY += faceYaw * 0.3f;
            if (!entitytitan.onGround && !this.isRiding) {
                this.BottomBody.rotateAngleZ = 0.0f;
                this.BottomMiddle.rotateAngleZ = 0.0f;
                this.BottomTop.rotateAngleZ = 0.0f;
                this.Head.rotateAngleZ = 0.0f;
                this.Head.rotateAngleX -= entitytitan.limbSwingAmount;
                this.BottomBody.rotateAngleX += entitytitan.limbSwingAmount;
                this.Leftfrontupperleg.rotateAngleY = -0.25f;
                this.Rightbackupperleg.rotateAngleY = 2.75f;
                this.Leftbackupperleg.rotateAngleY = -2.75f;
                this.Rightfrontupperleg.rotateAngleY = 0.25f;
                this.Rightbackupperleg.rotateAngleX = -2.0f - MathHelper.cos((float)(f2 * 0.2f)) * 0.25f - (float)(entitytitan.motionY / 5.0) - entitytitan.limbSwingAmount;
                this.Leftbackupperleg.rotateAngleX = -2.0f - MathHelper.cos((float)(f2 * 0.2f - (float)Math.PI)) * 0.25f - (float)(entitytitan.motionY / 5.0) - entitytitan.limbSwingAmount;
                this.Rightfrontupperleg.rotateAngleX = -2.0f - MathHelper.cos((float)(f2 * 0.2f)) * 0.25f - (float)(entitytitan.motionY / 5.0) + entitytitan.limbSwingAmount;
                this.Leftfrontupperleg.rotateAngleX = -2.0f - MathHelper.cos((float)(f2 * 0.2f - (float)Math.PI)) * 0.25f - (float)(entitytitan.motionY / 5.0) + entitytitan.limbSwingAmount;
            }
            if (entitytitan.getAnimID() == 1) {
                switch (entitytitan.antiTitanAttackAnimeID) {
                    case 0: {
                        this.animateAntiTitanAttack1();
                        break;
                    }
                    case 1: {
                        this.animateAntiTitanAttack2();
                        break;
                    }
                    case 2: {
                        this.animateAntiTitanAttack3();
                        break;
                    }
                    case 3: {
                        this.animateAntiTitanAttack4();
                    }
                }
            }
            this.animateStunned();
            this.animateThunderClap();
            this.animateSpit();
            this.animateKick();
            this.animateStomp();
            this.animateAttackStomp();
            this.animateHeadSlam();
            this.animateBirth();
        } else {
            this.animateDeath();
        }
    }

    private void animateAntiTitanAttack1() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, -3.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -4.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -4.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.rotate(this.Head, -1.0f, -1.2f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.75f, 0.6f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.75f, 0.6f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.75f, -0.75f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -2.25f, -0.75f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -2.25f, 0.75f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.Head, 0.5f, 0.75f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.75f, 0.75f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.75f, 0.5f, 0.0f);
        this.animator.rotate(this.BottomBody, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack2() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, -3.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -4.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -4.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.rotate(this.Head, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 1.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.5f, -0.75f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.5f, 0.75f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, -8.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.Head, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, -1.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack3() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 4.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -4.0f, -0.5f, -1.3f);
        this.animator.rotate(this.Leftfrontupperleg, -4.0f, 0.5f, 1.3f);
        this.animator.rotate(this.Rightbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, -8.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, -8.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, -8.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, -8.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, -8.0f);
        this.animator.rotate(this.Head, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, -0.5f, -1.3f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.5f, 1.3f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAntiTitanAttack4() {
        this.animator.setAnim(1);
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, -3.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -4.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -4.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -2.0f, 4.0f);
        this.animator.rotate(this.Head, -1.0f, 1.2f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.75f, -0.6f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.75f, -0.6f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.75f, 0.75f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -2.25f, -0.75f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -2.25f, 0.75f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 1.0f, -8.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, -8.0f);
        this.animator.rotate(this.Head, 0.5f, -0.75f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.75f, -0.75f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.75f, -0.5f, 0.0f);
        this.animator.rotate(this.BottomBody, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(10);
    }

    private void animateAttackStomp() {
        this.animator.setAnim(2);
        this.animator.startPhase(25);
        this.animator.rotate(this.Head, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.25f, 0.5f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.25f, 0.5f);
        this.animator.rotate(this.Rightfrontupperleg, -1.5f, 0.75f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -1.5f, -0.75f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.25f, -0.5f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.25f, -0.5f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.75f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.0f, -0.75f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(5);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -2.0f, 0.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, -0.5f);
        this.animator.rotate(this.BottomMiddle, -0.5f, -0.25f, -0.5f);
        this.animator.rotate(this.BottomBody, -0.5f, -0.25f, -0.5f);
        this.animator.rotate(this.Leftfrontupperleg, -1.5f, -0.75f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -1.5f, 0.75f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.5f);
        this.animator.rotate(this.BottomMiddle, 0.5f, -0.25f, 0.5f);
        this.animator.rotate(this.BottomBody, 0.5f, -0.25f, 0.5f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, -0.75f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.0f, 0.75f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(20);
        this.animator.resetPhase(20);
    }

    private void animateStomp() {
        this.animator.setAnim(3);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.5f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0f, 1.0f, -3.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, -2.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }

    private void animateHeadSlam() {
        this.animator.setAnim(4);
        this.animator.startPhase(10);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.3f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(15);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(30);
    }

    private void animateKick() {
        this.animator.setAnim(5);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, -1.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.25f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.5f, 1.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.75f, -1.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.75f, -1.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -1.0f, 1.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.25f, -1.5f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.25f, -0.75f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.25f, -0.75f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateSpit() {
        this.animator.setAnim(6);
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.25f, 0.0f, 0.0f);
        this.animator.move(this.BottomBody, 0.0f, -0.5f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateThunderClap() {
        this.animator.setAnim(7);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.5f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.35f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.35f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.25f, -0.5f, -1.3f);
        this.animator.rotate(this.Leftfrontupperleg, -1.25f, 0.5f, 1.3f);
        this.animator.rotate(this.Rightbackupperleg, 0.35f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.35f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(25);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -2.5f, -0.5f, -1.3f);
        this.animator.rotate(this.Leftfrontupperleg, -2.5f, 0.5f, 1.3f);
        this.animator.rotate(this.Rightbackupperleg, 0.35f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.35f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(5);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.rotate(this.Head, 2.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.75f, -0.5f, -1.3f);
        this.animator.rotate(this.Leftfrontupperleg, -0.75f, 0.5f, 1.3f);
        this.animator.rotate(this.Rightbackupperleg, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.4f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0f, 1.0f, -3.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 1.0f, -2.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, -2.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, -2.0f);
        this.animator.rotate(this.Head, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.5f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.1f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(50);
    }

    private void animateStunned() {
        this.animator.setAnim(8);
        this.animator.startPhase(0);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, 1.0f);
        this.animator.rotate(this.Head, 1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.2f, 0.25f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.2f, -0.25f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -3.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -3.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, -1.0f, 1.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.25f, 0.35f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.25f, -0.35f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0f, -1.0f, 1.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, -2.0f, 1.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, 1.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, 1.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.25f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(30);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(300);
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, 1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, 1.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(20);
    }

    private void animateDeath() {
        this.animator.setAnim(10);
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, -4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, -4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, -4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, -4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, -4.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.25f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, -0.25f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.2f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.2f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 1.0f, 0.0f, 2.0f);
        this.animator.rotate(this.Leftbackupperleg, 1.0f, 0.0f, -2.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.rotate(this.Head, 0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.25f, 0.25f, 0.0f);
        this.animator.rotate(this.BottomBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -1.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(10);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 4.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, -0.5f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.5f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(1720);
        this.animator.resetPhase(0);
    }

    private void animateBirth() {
        this.animator.setAnim(13);
        this.animator.startPhase(0);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.setStationaryPhase(60);
        this.animator.startPhase(60);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -1.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(40);
        this.animator.move(this.BottomBody, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 6.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 7.0f, 0.0f);
        this.animator.rotate(this.Head, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(80);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.5f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.5f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, -0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, -0.25f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, -0.75f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, 0.25f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, -0.3f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, 0.1f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, 0.2f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.startPhase(20);
        this.animator.move(this.BottomBody, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.move(this.Leftbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Head, -0.5f, -0.25f, 0.0f);
        this.animator.rotate(this.BottomTop, 0.25f, 0.0f, 0.3f);
        this.animator.rotate(this.BottomMiddle, 0.25f, 0.0f, -0.1f);
        this.animator.rotate(this.BottomBody, 0.25f, 0.0f, -0.2f);
        this.animator.rotate(this.Rightfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackupperleg, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightfrontfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Leftbackfoot, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackcalf, 0.0f, 0.0f, 0.0f);
        this.animator.rotate(this.Rightbackfoot, 0.0f, 0.0f, 0.0f);
        this.animator.endPhase();
        this.animator.resetPhase(40);
    }
}

